-- MessageType;
-- @author crazyjohn;

MessageType = {}

	-- CG_ADMIN_COMMAND
	MessageType.CG_ADMIN_COMMAND = 2001
	-- GC_SYSTEM_MESSAGE
	MessageType.GC_SYSTEM_MESSAGE = 2002
	-- GC_WAITING_START
	MessageType.GC_WAITING_START = 2003
	-- GC_WAITING_OVER
	MessageType.GC_WAITING_OVER = 2004
	-- GC_COMMON_ROLE_EFFECT
	MessageType.GC_COMMON_ROLE_EFFECT = 2005
	-- GC_COMMON_CHARGE
	MessageType.GC_COMMON_CHARGE = 2006
	-- GC_PING
	MessageType.GC_PING = 2007
	-- CG_PING
	MessageType.CG_PING = 2008
	-- GC_SYSTEM_NOTICE
	MessageType.GC_SYSTEM_NOTICE = 2009
	-- CG_HANDSHAKE
	MessageType.CG_HANDSHAKE = 2010
	-- GC_HANDSHAKE
	MessageType.GC_HANDSHAKE = 2011
	-- GC_SHOW_OPTION_DLG
	MessageType.GC_SHOW_OPTION_DLG = 2012
	-- CG_SELECT_OPTION
	MessageType.CG_SELECT_OPTION = 2013
	-- GC_COMMON_ASK_AND_ANSWER_URL
	MessageType.GC_COMMON_ASK_AND_ANSWER_URL = 2014
	-- CG_PLAYER_LOGIN
	MessageType.CG_PLAYER_LOGIN = 2351
	-- GC_PLAYER_LOGIN_RESULT
	MessageType.GC_PLAYER_LOGIN_RESULT = 2352
	-- CG_GET_CHAR_LIST
	MessageType.CG_GET_CHAR_LIST = 2353
	-- GC_CHAR_LIST
	MessageType.GC_CHAR_LIST = 2354
	-- CG_SELECT_CHAR
	MessageType.CG_SELECT_CHAR = 2355
	-- CG_CREATE_CHAR
	MessageType.CG_CREATE_CHAR = 2356
	-- GC_CREATE_CHAR_RESULT
	MessageType.GC_CREATE_CHAR_RESULT = 2357
	-- GC_ENTER_SCENE
	MessageType.GC_ENTER_SCENE = 2358
	-- CG_ENTER_SCENE_READY
	MessageType.CG_ENTER_SCENE_READY = 2359
	-- GC_CHARACTER_TEMPLATE
	MessageType.GC_CHARACTER_TEMPLATE = 2360
	-- CG_AUTO_NAME
	MessageType.CG_AUTO_NAME = 2361
	-- GC_AUTO_NAME
	MessageType.GC_AUTO_NAME = 2362
	-- CG_BUY_ENERGY
	MessageType.CG_BUY_ENERGY = 2363
	-- CG_RECOVER_ENERGY
	MessageType.CG_RECOVER_ENERGY = 2364
	-- GC_RECOVER_ENERGY
	MessageType.GC_RECOVER_ENERGY = 2365
	-- GC_OPEN_GAME_FUNCS
	MessageType.GC_OPEN_GAME_FUNCS = 2366
	-- GC_FUNCTION_INFO
	MessageType.GC_FUNCTION_INFO = 2367
	-- GC_BATTLE_POP
	MessageType.GC_BATTLE_POP = 2368
	-- GC_DIRECT_TO_AREA_SCENE
	MessageType.GC_DIRECT_TO_AREA_SCENE = 2369
	-- CG_PLAYER_COOLIE_LOGIN
	MessageType.CG_PLAYER_COOLIE_LOGIN = 2370
	-- CG_PLAYER_HEART_BEAT
	MessageType.CG_PLAYER_HEART_BEAT = 2371
	-- GC_CLOSE_GAME_FUNCS
	MessageType.GC_CLOSE_GAME_FUNCS = 2372
	-- GC_FUNC_NOTIFIES
	MessageType.GC_FUNC_NOTIFIES = 2373
	-- GC_FUNC_NOTIFY
	MessageType.GC_FUNC_NOTIFY = 2374
	-- GC_PROPERTY_CHANGED_NUMBER
	MessageType.GC_PROPERTY_CHANGED_NUMBER = 2701
	-- GC_PROPERTY_CHANGED_STRING
	MessageType.GC_PROPERTY_CHANGED_STRING = 2702
	-- GC_CHARACTER_INFO
	MessageType.GC_CHARACTER_INFO = 2703
	-- GC_CHARACTER_PROPERTIES
	MessageType.GC_CHARACTER_PROPERTIES = 2704
	-- CG_DISTRIBUTE_PROPERTY_POINT
	MessageType.CG_DISTRIBUTE_PROPERTY_POINT = 2705
	-- GC_HUMAN_LEVEL_UP
	MessageType.GC_HUMAN_LEVEL_UP = 2706
	-- CG_CHARACTER_SHOW_INFO
	MessageType.CG_CHARACTER_SHOW_INFO = 2707
	-- GC_CHARACTER_SHOW_INFO
	MessageType.GC_CHARACTER_SHOW_INFO = 2708
	-- CG_SHOW_CHARACTER_PANEL
	MessageType.CG_SHOW_CHARACTER_PANEL = 2709
	-- CG_RESET_PROPERTY_POINT
	MessageType.CG_RESET_PROPERTY_POINT = 2710
	-- GC_HUMAN_LEVEL_UP_INFO
	MessageType.GC_HUMAN_LEVEL_UP_INFO = 2711
	-- CG_CHAT_MSG
	MessageType.CG_CHAT_MSG = 2751
	-- GC_CHAT_MSG
	MessageType.GC_CHAT_MSG = 2752
	-- CG_CLICK_BUILDING
	MessageType.CG_CLICK_BUILDING = 2801
	-- CG_CLICK_BUILDING_FUNC
	MessageType.CG_CLICK_BUILDING_FUNC = 2802
	-- GC_SHOW_BUILDING_FUNC
	MessageType.GC_SHOW_BUILDING_FUNC = 2803
	-- GC_BUILDING_LIST
	MessageType.GC_BUILDING_LIST = 2804
	-- CG_UPGRADE_BUILDING
	MessageType.CG_UPGRADE_BUILDING = 2805
	-- GC_SHOW_BUILDING_UPGRADE_PANEL
	MessageType.GC_SHOW_BUILDING_UPGRADE_PANEL = 2806
	-- CG_BAG_TIDY
	MessageType.CG_BAG_TIDY = 2851
	-- GC_BAG_UPDATE
	MessageType.GC_BAG_UPDATE = 2852
	-- CG_REMOVE_ITEM
	MessageType.CG_REMOVE_ITEM = 2853
	-- GC_REMOVE_ITEM
	MessageType.GC_REMOVE_ITEM = 2854
	-- CG_MOVE_ITEM
	MessageType.CG_MOVE_ITEM = 2855
	-- GC_MOVE_ITEM
	MessageType.GC_MOVE_ITEM = 2856
	-- GC_ITEM_UPDATE
	MessageType.GC_ITEM_UPDATE = 2857
	-- CG_QUERY_BAG_UPGRADE_PRICE
	MessageType.CG_QUERY_BAG_UPGRADE_PRICE = 2858
	-- GC_BAG_UPGRADE_PRICE
	MessageType.GC_BAG_UPGRADE_PRICE = 2859
	-- CG_BAG_UPGRADE
	MessageType.CG_BAG_UPGRADE = 2860
	-- GC_BAG_UPGRADE_RESULT
	MessageType.GC_BAG_UPGRADE_RESULT = 2861
	-- CG_ITEM_USE
	MessageType.CG_ITEM_USE = 2862
	-- CG_BUY_MALL_ITEM
	MessageType.CG_BUY_MALL_ITEM = 2901
	-- CG_SHOW_MALL_ITEM
	MessageType.CG_SHOW_MALL_ITEM = 2902
	-- GC_SHOW_MALL_ITEM
	MessageType.GC_SHOW_MALL_ITEM = 2903
	-- CG_SHOW_MALL_ITEM_LIST
	MessageType.CG_SHOW_MALL_ITEM_LIST = 2904
	-- GC_SHOW_MALL_ITEM_LIST
	MessageType.GC_SHOW_MALL_ITEM_LIST = 2905
	-- GC_BUY_MALL_ITEM
	MessageType.GC_BUY_MALL_ITEM = 2906
	-- CG_ASK_MALL_ITEM
	MessageType.CG_ASK_MALL_ITEM = 2907
	-- GC_ASK_MALL_ITEM
	MessageType.GC_ASK_MALL_ITEM = 2908
	-- GC_ASK_MALL_ITEM_INFO
	MessageType.GC_ASK_MALL_ITEM_INFO = 2909
	-- GC_BULLETIN_LIST
	MessageType.GC_BULLETIN_LIST = 2951
	-- GC_BULLETIN_STOP
	MessageType.GC_BULLETIN_STOP = 2952
	-- GC_CD_QUEUE_INFOS
	MessageType.GC_CD_QUEUE_INFOS = 3001
	-- CG_REMOVE_CD
	MessageType.CG_REMOVE_CD = 3002
	-- GC_CD_QUEUE_INFO
	MessageType.GC_CD_QUEUE_INFO = 3003
	-- CG_CD_SPEED_UP
	MessageType.CG_CD_SPEED_UP = 3004
	-- GC_CD_SPEED_UP
	MessageType.GC_CD_SPEED_UP = 3005
	-- GC_QUEST_LIST
	MessageType.GC_QUEST_LIST = 3051
	-- CG_FINISH_QUEST
	MessageType.CG_FINISH_QUEST = 3052
	-- GC_QUEST_STATE
	MessageType.GC_QUEST_STATE = 3053
	-- GC_DAILY_QUEST_LIST
	MessageType.GC_DAILY_QUEST_LIST = 3054
	-- GC_SINGLE_QUEST_UPDATE
	MessageType.GC_SINGLE_QUEST_UPDATE = 3055
	-- CG_GET_DAILY_QUEST_LIST
	MessageType.CG_GET_DAILY_QUEST_LIST = 3056
	-- GC_APPEND_NEW_QUESTS
	MessageType.GC_APPEND_NEW_QUESTS = 3057
	-- GC_UPDATE_QUEST_COUNTER
	MessageType.GC_UPDATE_QUEST_COUNTER = 3058
	-- GC_UPDATE_DAILY_QUEST_SCORE
	MessageType.GC_UPDATE_DAILY_QUEST_SCORE = 3059
	-- CG_OPEN_DAILY_QUEST_REWARD_BOX
	MessageType.CG_OPEN_DAILY_QUEST_REWARD_BOX = 3060
	-- GC_DAILY_QUEST_REWARD_BOX_STATE_UPDATE
	MessageType.GC_DAILY_QUEST_REWARD_BOX_STATE_UPDATE = 3061
	-- GC_DAILY_QUEST_STATE
	MessageType.GC_DAILY_QUEST_STATE = 3062
	-- CG_RECEIVE_DAILY_QUEST
	MessageType.CG_RECEIVE_DAILY_QUEST = 3063
	-- CG_AUTO_COMPLETE_DAILY_QUEST
	MessageType.CG_AUTO_COMPLETE_DAILY_QUEST = 3064
	-- GC_AUTO_COMPLETE_DAILY_QUEST
	MessageType.GC_AUTO_COMPLETE_DAILY_QUEST = 3065
	-- CG_ABORT_DAILY_QUEST
	MessageType.CG_ABORT_DAILY_QUEST = 3066
	-- CG_APPLY_QUICKLY_COMPLETE_DAILY_QUEST
	MessageType.CG_APPLY_QUICKLY_COMPLETE_DAILY_QUEST = 3067
	-- GC_APPLY_QUICKLY_COMPLETE_DAILY_QUEST
	MessageType.GC_APPLY_QUICKLY_COMPLETE_DAILY_QUEST = 3068
	-- CG_QUICKLY_COMPLETE_DAILY_QUEST
	MessageType.CG_QUICKLY_COMPLETE_DAILY_QUEST = 3069
	-- CG_GET_DAILY_QUEST_REWARD
	MessageType.CG_GET_DAILY_QUEST_REWARD = 3070
	-- GC_GET_DAILY_QUEST_REWARD
	MessageType.GC_GET_DAILY_QUEST_REWARD = 3071
	-- CG_REFRESH_DAILY_QUEST_LIST
	MessageType.CG_REFRESH_DAILY_QUEST_LIST = 3072
	-- GC_REFRESH_DAILY_QUEST_LIST
	MessageType.GC_REFRESH_DAILY_QUEST_LIST = 3073
	-- CG_BUY_SHOP_ITEM
	MessageType.CG_BUY_SHOP_ITEM = 3101
	-- CG_SELL_SHOP_ITEM
	MessageType.CG_SELL_SHOP_ITEM = 3102
	-- CG_SHOW_SHOP_ITEM_LIST
	MessageType.CG_SHOW_SHOP_ITEM_LIST = 3103
	-- GC_SHOW_SHOP_ITEM_LIST
	MessageType.GC_SHOW_SHOP_ITEM_LIST = 3104
	-- CG_SHOW_SPECIAL_SHOP_PANEL
	MessageType.CG_SHOW_SPECIAL_SHOP_PANEL = 3105
	-- GC_SHOW_SPECIAL_SHOP_PANEL
	MessageType.GC_SHOW_SPECIAL_SHOP_PANEL = 3106
	-- CG_BUY_SPECIAL_SHOP_ITEM
	MessageType.CG_BUY_SPECIAL_SHOP_ITEM = 3107
	-- GC_BUY_SPECIAL_SHOP_ITEM
	MessageType.GC_BUY_SPECIAL_SHOP_ITEM = 3108
	-- CG_REFRESH_SPECIAL_SHOP
	MessageType.CG_REFRESH_SPECIAL_SHOP = 3109
	-- CG_ASTROLOGICAL
	MessageType.CG_ASTROLOGICAL = 3151
	-- CG_LEVY
	MessageType.CG_LEVY = 3201
	-- CG_OPEN_MAIN_CITY_PANEL
	MessageType.CG_OPEN_MAIN_CITY_PANEL = 3202
	-- GC_UPDATE_MAIN_CITY_PANEL
	MessageType.GC_UPDATE_MAIN_CITY_PANEL = 3203
	-- CG_COLLECT_MAGIC_STONE
	MessageType.CG_COLLECT_MAGIC_STONE = 3204
	-- GC_COLLECT_MAGIC_STONE
	MessageType.GC_COLLECT_MAGIC_STONE = 3205
	-- GC_COLLECT_MAGIC_STONE_COMPLETE
	MessageType.GC_COLLECT_MAGIC_STONE_COMPLETE = 3206
	-- GC_LEVY
	MessageType.GC_LEVY = 3207
	-- CG_LEVY_BET
	MessageType.CG_LEVY_BET = 3208
	-- GC_LEVY_BET
	MessageType.GC_LEVY_BET = 3209
	-- CG_GET_MAIN_CITY_MONSTER_INFO
	MessageType.CG_GET_MAIN_CITY_MONSTER_INFO = 3210
	-- GC_SEND_MAIN_CITY_MONSTER_INFO
	MessageType.GC_SEND_MAIN_CITY_MONSTER_INFO = 3211
	-- CG_BATTLE_MAIN_CITY_MONSTER
	MessageType.CG_BATTLE_MAIN_CITY_MONSTER = 3212
	-- GC_SHOW_HARVEST_MINE_INFO
	MessageType.GC_SHOW_HARVEST_MINE_INFO = 3301
	-- GC_SHOW_HARVEST_WOOD_INFO
	MessageType.GC_SHOW_HARVEST_WOOD_INFO = 3302
	-- CG_HARVEST
	MessageType.CG_HARVEST = 3303
	-- GC_HARVEST_MINE
	MessageType.GC_HARVEST_MINE = 3304
	-- GC_HARVEST_WOOD
	MessageType.GC_HARVEST_WOOD = 3305
	-- CG_ADD_HARVEST_NUM
	MessageType.CG_ADD_HARVEST_NUM = 3306
	-- GC_ADD_HARVEST_NUM
	MessageType.GC_ADD_HARVEST_NUM = 3307
	-- CG_CHANGE_HARVEST_COST_ALERT_STATE
	MessageType.CG_CHANGE_HARVEST_COST_ALERT_STATE = 3308
	-- GC_HARVEST_ENCOUNTER
	MessageType.GC_HARVEST_ENCOUNTER = 3309
	-- CG_HARVEST_ENCOUNTER_CHOICE
	MessageType.CG_HARVEST_ENCOUNTER_CHOICE = 3310
	-- GC_HARVEST_MINE_ENCOUNTER_RESULT
	MessageType.GC_HARVEST_MINE_ENCOUNTER_RESULT = 3311
	-- GC_HARVEST_WOOD_ENCOUNTER_RESULT
	MessageType.GC_HARVEST_WOOD_ENCOUNTER_RESULT = 3312
	-- CG_ALL_MINE_HARVEST
	MessageType.CG_ALL_MINE_HARVEST = 3313
	-- CG_REMOVE_ALL_MINE_CD
	MessageType.CG_REMOVE_ALL_MINE_CD = 3314
	-- GC_REMOVE_ALL_MINE_CD
	MessageType.GC_REMOVE_ALL_MINE_CD = 3315
	-- CG_REMOVE_ALL_MINE_CD_CONFIRM
	MessageType.CG_REMOVE_ALL_MINE_CD_CONFIRM = 3316
	-- CG_GEM_EMBED
	MessageType.CG_GEM_EMBED = 3351
	-- GC_GEM_EMBED
	MessageType.GC_GEM_EMBED = 3352
	-- CG_GEM_EXTRACT
	MessageType.CG_GEM_EXTRACT = 3353
	-- GC_GEM_EXTRACT
	MessageType.GC_GEM_EXTRACT = 3354
	-- GC_SHOW_GEM_EMBED_PANEL
	MessageType.GC_SHOW_GEM_EMBED_PANEL = 3355
	-- CG_GEM_PUNCH
	MessageType.CG_GEM_PUNCH = 3356
	-- GC_GEM_PUNCH
	MessageType.GC_GEM_PUNCH = 3357
	-- CG_PUT_EQUIP
	MessageType.CG_PUT_EQUIP = 3358
	-- GC_PUT_EQUIP
	MessageType.GC_PUT_EQUIP = 3359
	-- CG_EQUIP_UPGRADE
	MessageType.CG_EQUIP_UPGRADE = 3360
	-- CG_SELECT_EQUIP
	MessageType.CG_SELECT_EQUIP = 3361
	-- GC_SELECT_EQUIP
	MessageType.GC_SELECT_EQUIP = 3362
	-- GC_SHOW_EQUIP_UPGRADE_PANEL
	MessageType.GC_SHOW_EQUIP_UPGRADE_PANEL = 3363
	-- CG_SELECT_EQUIP_PAPER_TO_MAKE
	MessageType.CG_SELECT_EQUIP_PAPER_TO_MAKE = 3364
	-- GC_UPDATE_EQUIP_MAKE_PANEL
	MessageType.GC_UPDATE_EQUIP_MAKE_PANEL = 3365
	-- CG_EQUIP_MAKE
	MessageType.CG_EQUIP_MAKE = 3366
	-- GC_EQUIP_MAKE
	MessageType.GC_EQUIP_MAKE = 3367
	-- GC_EQUIP_UPGRADE
	MessageType.GC_EQUIP_UPGRADE = 3368
	-- CG_SHOW_SOMETHING
	MessageType.CG_SHOW_SOMETHING = 3369
	-- GC_SHOW_ITEM
	MessageType.GC_SHOW_ITEM = 3370
	-- CG_GEM_PUNCH_CONFIRM
	MessageType.CG_GEM_PUNCH_CONFIRM = 3371
	-- GC_GEM_PUNCH_CONFIRM
	MessageType.GC_GEM_PUNCH_CONFIRM = 3372
	-- GC_ITEM_QUICK_BUY_INFO
	MessageType.GC_ITEM_QUICK_BUY_INFO = 3373
	-- CG_MATERIAL_GUIDE
	MessageType.CG_MATERIAL_GUIDE = 3374
	-- GC_MATERIAL_GUIDE
	MessageType.GC_MATERIAL_GUIDE = 3375
	-- CG_CHECK_EQUIP_MAKE
	MessageType.CG_CHECK_EQUIP_MAKE = 3376
	-- GC_CHECK_EQUIP_MAKE
	MessageType.GC_CHECK_EQUIP_MAKE = 3377
	-- CG_SELECT_EQUIP_TO_MAKE
	MessageType.CG_SELECT_EQUIP_TO_MAKE = 3378
	-- GC_SELECT_EQUIP_TO_MAKE
	MessageType.GC_SELECT_EQUIP_TO_MAKE = 3379
	-- GC_USE_NOSTRUM
	MessageType.GC_USE_NOSTRUM = 3380
	-- CG_SHOW_LUCK_FRIENDS
	MessageType.CG_SHOW_LUCK_FRIENDS = 3401
	-- GC_SHOW_LUCK_FRIENDS
	MessageType.GC_SHOW_LUCK_FRIENDS = 3402
	-- CG_ADD_FRIENDS
	MessageType.CG_ADD_FRIENDS = 3403
	-- CG_ADD_FRIEND
	MessageType.CG_ADD_FRIEND = 3404
	-- CG_REMOVE_FRIEND
	MessageType.CG_REMOVE_FRIEND = 3405
	-- CG_SHOW_FRIENDS
	MessageType.CG_SHOW_FRIENDS = 3406
	-- GC_SHOW_FRIENDS
	MessageType.GC_SHOW_FRIENDS = 3407
	-- CG_FRIEND_CHAT
	MessageType.CG_FRIEND_CHAT = 3408
	-- GC_FRIEND_CHAT
	MessageType.GC_FRIEND_CHAT = 3409
	-- CG_SHOW_FRIEND_APPLY_LIST
	MessageType.CG_SHOW_FRIEND_APPLY_LIST = 3410
	-- GC_SHOW_FRIEND_APPLY_LIST
	MessageType.GC_SHOW_FRIEND_APPLY_LIST = 3411
	-- CG_SHOW_SELF_APPLY_LIST
	MessageType.CG_SHOW_SELF_APPLY_LIST = 3412
	-- GC_SHOW_SELF_APPLY_LIST
	MessageType.GC_SHOW_SELF_APPLY_LIST = 3413
	-- CG_ADD_FRIEND_AGREE
	MessageType.CG_ADD_FRIEND_AGREE = 3414
	-- CG_ADD_FRIEND_REFUSE
	MessageType.CG_ADD_FRIEND_REFUSE = 3415
	-- CG_GIVE_ENERGY
	MessageType.CG_GIVE_ENERGY = 3416
	-- CG_GET_ENERGY
	MessageType.CG_GET_ENERGY = 3417
	-- GC_FRIEND_APPLY
	MessageType.GC_FRIEND_APPLY = 3418
	-- CG_CANCEL_APPLY_FRIEND
	MessageType.CG_CANCEL_APPLY_FRIEND = 3419
	-- GC_GIVE_ENERGY
	MessageType.GC_GIVE_ENERGY = 3420
	-- GC_REMOVE_FRIEND
	MessageType.GC_REMOVE_FRIEND = 3421
	-- GC_UPDATE_FRIEND_INFO
	MessageType.GC_UPDATE_FRIEND_INFO = 3422
	-- GC_REMOVE_APPLY
	MessageType.GC_REMOVE_APPLY = 3423
	-- GC_ADD_FRIEND_INFO
	MessageType.GC_ADD_FRIEND_INFO = 3424
	-- GC_LEFT_FRIEND_REWARD_TIMES
	MessageType.GC_LEFT_FRIEND_REWARD_TIMES = 3425
	-- GC_FRIEND_OFFLINE
	MessageType.GC_FRIEND_OFFLINE = 3426
	-- CG_SHOW_LATEST_FRIENDS
	MessageType.CG_SHOW_LATEST_FRIENDS = 3427
	-- GC_SHOW_LATEST_FRIENDS
	MessageType.GC_SHOW_LATEST_FRIENDS = 3428
	-- CG_SHOW_FRIEND_BATTLEINFOS
	MessageType.CG_SHOW_FRIEND_BATTLEINFOS = 3429
	-- GC_SHOW_FRIEND_BATTLEINFOS
	MessageType.GC_SHOW_FRIEND_BATTLEINFOS = 3430
	-- GC_ADD_FRIEND_BATTLEINFO
	MessageType.GC_ADD_FRIEND_BATTLEINFO = 3431
	-- GC_RECOMMEND_FRIEND_ADD_INFO
	MessageType.GC_RECOMMEND_FRIEND_ADD_INFO = 3432
	-- CG_OPEN_PRIVATE_CHAT_PANEL
	MessageType.CG_OPEN_PRIVATE_CHAT_PANEL = 3433
	-- GC_OPEN_PRIVATE_CHAT_PANEL
	MessageType.GC_OPEN_PRIVATE_CHAT_PANEL = 3434
	-- GC_FRIEND_BATTLE_RESULT
	MessageType.GC_FRIEND_BATTLE_RESULT = 3435
	-- CG_SHOW_RANK
	MessageType.CG_SHOW_RANK = 3451
	-- GC_SHOW_LEVEL_RANK
	MessageType.GC_SHOW_LEVEL_RANK = 3452
	-- GC_SHOW_TITLE_RANK
	MessageType.GC_SHOW_TITLE_RANK = 3453
	-- GC_SHOW_HONOR_RANK
	MessageType.GC_SHOW_HONOR_RANK = 3454
	-- GC_SHOW_VIP_RANK
	MessageType.GC_SHOW_VIP_RANK = 3455
	-- GC_SHOW_LEGION_LEVEL_RANK
	MessageType.GC_SHOW_LEGION_LEVEL_RANK = 3456
	-- GC_SHOW_LEGION_MEMBER_RANK
	MessageType.GC_SHOW_LEGION_MEMBER_RANK = 3457
	-- CG_GET_RANK_REWARD
	MessageType.CG_GET_RANK_REWARD = 3458
	-- GC_GET_LEVEL_RANK_REWARD
	MessageType.GC_GET_LEVEL_RANK_REWARD = 3459
	-- CG_SHOW_MAILLIST
	MessageType.CG_SHOW_MAILLIST = 3501
	-- GC_SHOW_MAILLIST
	MessageType.GC_SHOW_MAILLIST = 3502
	-- CG_SHOW_MAIL
	MessageType.CG_SHOW_MAIL = 3503
	-- GC_SHOW_MAIL
	MessageType.GC_SHOW_MAIL = 3504
	-- CG_PICKUP_ATTACHMENT
	MessageType.CG_PICKUP_ATTACHMENT = 3505
	-- GC_PICKUP_ATTACHMENT
	MessageType.GC_PICKUP_ATTACHMENT = 3506
	-- CG_DELETE_MAIL
	MessageType.CG_DELETE_MAIL = 3507
	-- GC_DELETE_MAIL
	MessageType.GC_DELETE_MAIL = 3508
	-- CG_SEND_MAIL
	MessageType.CG_SEND_MAIL = 3509
	-- GC_RECEIVE_MAIL
	MessageType.GC_RECEIVE_MAIL = 3510
	-- GC_SEND_MAIL
	MessageType.GC_SEND_MAIL = 3511
	-- CG_VIEW_HARVEST_GEM
	MessageType.CG_VIEW_HARVEST_GEM = 3551
	-- GC_VIEW_HARVEST_GEM
	MessageType.GC_VIEW_HARVEST_GEM = 3552
	-- CG_HARVEST_GEM
	MessageType.CG_HARVEST_GEM = 3553
	-- GC_HARVEST_GEM
	MessageType.GC_HARVEST_GEM = 3554
	-- GC_UPDATE_HARVEST_GEM
	MessageType.GC_UPDATE_HARVEST_GEM = 3555
	-- CG_SELECT_GEM_TO_SYNTHESIS
	MessageType.CG_SELECT_GEM_TO_SYNTHESIS = 3556
	-- GC_UPDATE_GEM_SYNTHESIS_PANEL
	MessageType.GC_UPDATE_GEM_SYNTHESIS_PANEL = 3557
	-- CG_GEM_SYNTHESIS
	MessageType.CG_GEM_SYNTHESIS = 3558
	-- GC_GEM_SYNTHESIS
	MessageType.GC_GEM_SYNTHESIS = 3559
	-- CG_SHOW_HOROSCOPE_PANEL
	MessageType.CG_SHOW_HOROSCOPE_PANEL = 3601
	-- GC_SHOW_HOROSCOPE_PANEL
	MessageType.GC_SHOW_HOROSCOPE_PANEL = 3602
	-- CG_HOROSCOPE_GAMBLE
	MessageType.CG_HOROSCOPE_GAMBLE = 3603
	-- GC_HOROSCOPE_GAMBLE
	MessageType.GC_HOROSCOPE_GAMBLE = 3604
	-- CG_HOROSCOPE_GAMBLE_AUTO
	MessageType.CG_HOROSCOPE_GAMBLE_AUTO = 3605
	-- GC_HOROSCOPE_GAMBLE_AUTO
	MessageType.GC_HOROSCOPE_GAMBLE_AUTO = 3606
	-- CG_HOROSCOPE_COMPOUND_CONFIRM
	MessageType.CG_HOROSCOPE_COMPOUND_CONFIRM = 3607
	-- GC_HOROSCOPE_COMPOUND
	MessageType.GC_HOROSCOPE_COMPOUND = 3608
	-- CG_HOROSCOPE_COMPOUND_AUTO
	MessageType.CG_HOROSCOPE_COMPOUND_AUTO = 3609
	-- GC_HOROSCOPE_COMPOUND_AUTO
	MessageType.GC_HOROSCOPE_COMPOUND_AUTO = 3610
	-- CG_HOROSCOPE_ON
	MessageType.CG_HOROSCOPE_ON = 3611
	-- CG_HOROSCOPE_OFF
	MessageType.CG_HOROSCOPE_OFF = 3612
	-- CG_HOROSCOPE_SWAP
	MessageType.CG_HOROSCOPE_SWAP = 3613
	-- GC_HOROSCOPE_REMOVE
	MessageType.GC_HOROSCOPE_REMOVE = 3614
	-- GC_HOROSCOPE_UPDATE
	MessageType.GC_HOROSCOPE_UPDATE = 3615
	-- GC_UPDATE_STARGAZERS
	MessageType.GC_UPDATE_STARGAZERS = 3616
	-- CG_HOROSCOPE_INTRODUCE
	MessageType.CG_HOROSCOPE_INTRODUCE = 3617
	-- GC_HOROSCOPE_INTRODUCE
	MessageType.GC_HOROSCOPE_INTRODUCE = 3618
	-- CG_HOROSCOPE_STORAGE_UPGRADE_PRICE
	MessageType.CG_HOROSCOPE_STORAGE_UPGRADE_PRICE = 3619
	-- GC_HOROSCOPE_STORAGE_UPGRADE_PRICE
	MessageType.GC_HOROSCOPE_STORAGE_UPGRADE_PRICE = 3620
	-- CG_HOROSCOPE_STORAGE_UPGRADE
	MessageType.CG_HOROSCOPE_STORAGE_UPGRADE = 3621
	-- GC_HOROSCOPE_STORAGE_UPGRADE
	MessageType.GC_HOROSCOPE_STORAGE_UPGRADE = 3622
	-- GC_HOROSCOPE_UPDATE_AND_REMOVE
	MessageType.GC_HOROSCOPE_UPDATE_AND_REMOVE = 3623
	-- GC_EQUIP_HOROSCOPE_INFOS
	MessageType.GC_EQUIP_HOROSCOPE_INFOS = 3624
	-- CG_HOROSCOPE_PICK_UP
	MessageType.CG_HOROSCOPE_PICK_UP = 3625
	-- CG_SHOW_TECHNOLOGY_INFO
	MessageType.CG_SHOW_TECHNOLOGY_INFO = 3651
	-- CG_UPGRADE_TECHNOLOGY
	MessageType.CG_UPGRADE_TECHNOLOGY = 3652
	-- GC_SHOW_TECHNOLOGY_PANEL
	MessageType.GC_SHOW_TECHNOLOGY_PANEL = 3653
	-- GC_SHOW_TECHNOLOGY_INFO
	MessageType.GC_SHOW_TECHNOLOGY_INFO = 3654
	-- GC_UPGRADE_TECHNOLOGY
	MessageType.GC_UPGRADE_TECHNOLOGY = 3655
	-- CG_SHOW_TECHNOLOGY_PANEL
	MessageType.CG_SHOW_TECHNOLOGY_PANEL = 3656
	-- GC_START_BATTLE_INFO
	MessageType.GC_START_BATTLE_INFO = 3701
	-- CG_START_BATTLE_WITH_MONSTER
	MessageType.CG_START_BATTLE_WITH_MONSTER = 3702
	-- CG_NORMAL_ATTACK
	MessageType.CG_NORMAL_ATTACK = 3703
	-- GC_START_BATTLE_ACTION
	MessageType.GC_START_BATTLE_ACTION = 3704
	-- GC_NORMAL_ATTACK
	MessageType.GC_NORMAL_ATTACK = 3705
	-- GC_UPDATE_CHESS_BOARD
	MessageType.GC_UPDATE_CHESS_BOARD = 3706
	-- GC_START_ACTION_TIMER
	MessageType.GC_START_ACTION_TIMER = 3707
	-- GC_CHOOSE_ACTION_TIMEOUT
	MessageType.GC_CHOOSE_ACTION_TIMEOUT = 3708
	-- CG_ANIMATION_OVER
	MessageType.CG_ANIMATION_OVER = 3709
	-- CG_BATTLE_RESOURCE_LOADED
	MessageType.CG_BATTLE_RESOURCE_LOADED = 3710
	-- GC_CHANGE_GEMS_COLOR
	MessageType.GC_CHANGE_GEMS_COLOR = 3711
	-- GC_BATTLE_FINISHED
	MessageType.GC_BATTLE_FINISHED = 3712
	-- GC_EXIT_BATTLE
	MessageType.GC_EXIT_BATTLE = 3713
	-- GC_BATTLE_UNIT_DEAD
	MessageType.GC_BATTLE_UNIT_DEAD = 3714
	-- GC_BATTLE_NEW_ROUND
	MessageType.GC_BATTLE_NEW_ROUND = 3715
	-- CG_START_BATTLE_WITH_FRIEND
	MessageType.CG_START_BATTLE_WITH_FRIEND = 3716
	-- GC_JOIN_BATTLE_REQUEST
	MessageType.GC_JOIN_BATTLE_REQUEST = 3717
	-- CG_JOIN_BATTLE_RESPONSE
	MessageType.CG_JOIN_BATTLE_RESPONSE = 3718
	-- GC_ADD_BATTLE_ACTION_TIME
	MessageType.GC_ADD_BATTLE_ACTION_TIME = 3719
	-- GC_CHESS_BOARD_INFO
	MessageType.GC_CHESS_BOARD_INFO = 3720
	-- CG_RESET_CHESSBOARD_ANIMATION_OVER
	MessageType.CG_RESET_CHESSBOARD_ANIMATION_OVER = 3721
	-- GC_DEBUG_CHESSBOARD_SYNC_ERROR
	MessageType.GC_DEBUG_CHESSBOARD_SYNC_ERROR = 3722
	-- GC_UPDATE_BLACK_GEM_ATTACK_ADD_RATE
	MessageType.GC_UPDATE_BLACK_GEM_ATTACK_ADD_RATE = 3723
	-- GC_BATTLE_WAITING_OTHER_UNIT_READY
	MessageType.GC_BATTLE_WAITING_OTHER_UNIT_READY = 3724
	-- GC_BAD_NET_ENVIRONMENT
	MessageType.GC_BAD_NET_ENVIRONMENT = 3725
	-- CG_BATTLE_CHAT
	MessageType.CG_BATTLE_CHAT = 3726
	-- GC_BATTLE_CHAT
	MessageType.GC_BATTLE_CHAT = 3727
	-- CG_REQUEST_HOSTING_BATTLE
	MessageType.CG_REQUEST_HOSTING_BATTLE = 3728
	-- GC_START_HOSTING_BATTLE
	MessageType.GC_START_HOSTING_BATTLE = 3729
	-- CG_REQUEST_BATTLE_GIVE_UP
	MessageType.CG_REQUEST_BATTLE_GIVE_UP = 3730
	-- GC_BATTLE_GIVE_UP
	MessageType.GC_BATTLE_GIVE_UP = 3731
	-- CG_ALREADY_LEAVE_BATTLE_SCENE
	MessageType.CG_ALREADY_LEAVE_BATTLE_SCENE = 3732
	-- CG_REQUEST_CANCEL_HOSTING_BATTLE
	MessageType.CG_REQUEST_CANCEL_HOSTING_BATTLE = 3733
	-- GC_CANCEL_HOSTING_BATTLE_SUCCEED
	MessageType.GC_CANCEL_HOSTING_BATTLE_SUCCEED = 3734
	-- GC_WAITTING_BATTLE_RESPONSE
	MessageType.GC_WAITTING_BATTLE_RESPONSE = 3735
	-- CG_USE_SKILL
	MessageType.CG_USE_SKILL = 3751
	-- GC_USE_SKILL
	MessageType.GC_USE_SKILL = 3752
	-- GC_EFFECT_DIRECT
	MessageType.GC_EFFECT_DIRECT = 3753
	-- GC_EFFECT_MISS
	MessageType.GC_EFFECT_MISS = 3754
	-- GC_START_BUFF_EFFECT
	MessageType.GC_START_BUFF_EFFECT = 3755
	-- GC_STOP_BUFF_EFFECT
	MessageType.GC_STOP_BUFF_EFFECT = 3756
	-- GC_UPDATE_BUFF_STATE
	MessageType.GC_UPDATE_BUFF_STATE = 3757
	-- GC_REPLACE_OLD_BUFF
	MessageType.GC_REPLACE_OLD_BUFF = 3758
	-- GC_CLEAR_BUFF
	MessageType.GC_CLEAR_BUFF = 3759
	-- GC_UPDATE_SKILL_STATE
	MessageType.GC_UPDATE_SKILL_STATE = 3760
	-- GC_ALL_SKILLS
	MessageType.GC_ALL_SKILLS = 3761
	-- GC_BATTLE_CARRIED_SKILLS
	MessageType.GC_BATTLE_CARRIED_SKILLS = 3762
	-- CG_EQUIP_SKILL
	MessageType.CG_EQUIP_SKILL = 3763
	-- CG_UNEQUIP_SKILL
	MessageType.CG_UNEQUIP_SKILL = 3764
	-- GC_UPDATE_SKILL_EQUIP_STATE
	MessageType.GC_UPDATE_SKILL_EQUIP_STATE = 3765
	-- GC_BATTLE_HP_CHANGED
	MessageType.GC_BATTLE_HP_CHANGED = 3766
	-- GC_BATTLE_MAGIC_CHANGED
	MessageType.GC_BATTLE_MAGIC_CHANGED = 3767
	-- CG_GET_SKILL_SLOTS_INFO
	MessageType.CG_GET_SKILL_SLOTS_INFO = 3768
	-- GC_SKILL_SLOTS_INFO
	MessageType.GC_SKILL_SLOTS_INFO = 3769
	-- CG_GET_SKILL_SLOT_TIP
	MessageType.CG_GET_SKILL_SLOT_TIP = 3770
	-- GC_SKILL_SLOT_INFO
	MessageType.GC_SKILL_SLOT_INFO = 3771
	-- CG_OPEN_SKILL_SLOT
	MessageType.CG_OPEN_SKILL_SLOT = 3772
	-- CG_DIRECT_OPEN_SKILL_SLOT
	MessageType.CG_DIRECT_OPEN_SKILL_SLOT = 3773
	-- GC_OPEN_SKILL_SLOT_RESULT
	MessageType.GC_OPEN_SKILL_SLOT_RESULT = 3774
	-- CG_STUDY_SKILL
	MessageType.CG_STUDY_SKILL = 3775
	-- CG_RESET_SKILLS
	MessageType.CG_RESET_SKILLS = 3776
	-- CG_SHOW_SKILL_PANEL
	MessageType.CG_SHOW_SKILL_PANEL = 3777
	-- CG_OPEN_TRAINING_PANEL
	MessageType.CG_OPEN_TRAINING_PANEL = 3801
	-- GC_UPDATE_TRAINING_PANEL
	MessageType.GC_UPDATE_TRAINING_PANEL = 3802
	-- CG_TRAINING_BEGIN
	MessageType.CG_TRAINING_BEGIN = 3803
	-- GC_TRAINING_BEGIN_UPDATE
	MessageType.GC_TRAINING_BEGIN_UPDATE = 3804
	-- CG_COLLECT_TRAINING_EXP
	MessageType.CG_COLLECT_TRAINING_EXP = 3805
	-- GC_COLLECT_TRAINING_EXP
	MessageType.GC_COLLECT_TRAINING_EXP = 3806
	-- GC_UPDATE_TRAINING_STATE
	MessageType.GC_UPDATE_TRAINING_STATE = 3807
	-- CG_CRYSTAL_EXCHANGE
	MessageType.CG_CRYSTAL_EXCHANGE = 3851
	-- CG_SHOW_CRYSTAL_EXCHANGE_PANEL
	MessageType.CG_SHOW_CRYSTAL_EXCHANGE_PANEL = 3852
	-- GC_SHOW_CRYSTAL_EXCHANGE_PANEL
	MessageType.GC_SHOW_CRYSTAL_EXCHANGE_PANEL = 3853
	-- GC_CRYSTAL_EXCHANGE_TIMES
	MessageType.GC_CRYSTAL_EXCHANGE_TIMES = 3854
	-- CG_GET_REWARD
	MessageType.CG_GET_REWARD = 3901
	-- GC_GET_REWARD
	MessageType.GC_GET_REWARD = 3902
	-- CG_GET_SPECIAL_REWARD
	MessageType.CG_GET_SPECIAL_REWARD = 3903
	-- GC_GET_SPECIAL_REWARD
	MessageType.GC_GET_SPECIAL_REWARD = 3904
	-- CG_SHOW_LOGIN_REWARD_PANEL
	MessageType.CG_SHOW_LOGIN_REWARD_PANEL = 3905
	-- GC_SHOW_LOGIN_REWARD_PANEL
	MessageType.GC_SHOW_LOGIN_REWARD_PANEL = 3906
	-- GC_HAS_LOGIN_REWARD
	MessageType.GC_HAS_LOGIN_REWARD = 3907
	-- CG_GET_ONLINE_REWARD
	MessageType.CG_GET_ONLINE_REWARD = 3951
	-- GC_SHOW_ONLINE_REWARD
	MessageType.GC_SHOW_ONLINE_REWARD = 3952
	-- GC_ONLINE_REWARD_END
	MessageType.GC_ONLINE_REWARD_END = 3953
	-- CG_LOTTERY
	MessageType.CG_LOTTERY = 4001
	-- CG_SHOW_TURNTABLE_PANEL
	MessageType.CG_SHOW_TURNTABLE_PANEL = 4002
	-- GC_LOTTERY
	MessageType.GC_LOTTERY = 4003
	-- GC_SHOW_TURNTABLE_PANEL
	MessageType.GC_SHOW_TURNTABLE_PANEL = 4004
	-- GC_GUIDE_INFO
	MessageType.GC_GUIDE_INFO = 4051
	-- CG_ENTER_BATTLE_SCENE
	MessageType.CG_ENTER_BATTLE_SCENE = 4101
	-- GC_ENTER_BATTLE_SCENE
	MessageType.GC_ENTER_BATTLE_SCENE = 4102
	-- CG_ATTACK_STAGE
	MessageType.CG_ATTACK_STAGE = 4103
	-- GC_ATTACK_STAGE
	MessageType.GC_ATTACK_STAGE = 4104
	-- GC_PASS_STAGE_REWARD
	MessageType.GC_PASS_STAGE_REWARD = 4105
	-- CG_GET_PASS_STAGE_REWARD
	MessageType.CG_GET_PASS_STAGE_REWARD = 4106
	-- GC_GET_PASS_STAGE_REWARD
	MessageType.GC_GET_PASS_STAGE_REWARD = 4107
	-- CG_STAGE_INFO
	MessageType.CG_STAGE_INFO = 4108
	-- GC_STAGE_INFO
	MessageType.GC_STAGE_INFO = 4109
	-- CG_AUTO_ATTACK_STAGE
	MessageType.CG_AUTO_ATTACK_STAGE = 4110
	-- GC_STAGE_DRAMA_INFO
	MessageType.GC_STAGE_DRAMA_INFO = 4111
	-- CG_CLICK_STAGE
	MessageType.CG_CLICK_STAGE = 4112
	-- CG_SHOW_STAGE_MAPS
	MessageType.CG_SHOW_STAGE_MAPS = 4113
	-- GC_SHOW_STAGE_MAPS
	MessageType.GC_SHOW_STAGE_MAPS = 4114
	-- CG_GET_ALL_BATTLE_REWARD
	MessageType.CG_GET_ALL_BATTLE_REWARD = 4115
	-- CG_GET_STAGE_STAR_REWARD
	MessageType.CG_GET_STAGE_STAR_REWARD = 4116
	-- GC_GET_STAGE_STAR_REWARD
	MessageType.GC_GET_STAGE_STAR_REWARD = 4117
	-- GC_STAR_AND_REWARD_STATE
	MessageType.GC_STAR_AND_REWARD_STATE = 4118
	-- CG_SHOW_MAP_PERFECT_REWARD_PANEL
	MessageType.CG_SHOW_MAP_PERFECT_REWARD_PANEL = 4119
	-- GC_SHOW_MAP_PERFECT_REWARD_PANEL
	MessageType.GC_SHOW_MAP_PERFECT_REWARD_PANEL = 4120
	-- CG_GET_MAP_PERFECT_REWARD
	MessageType.CG_GET_MAP_PERFECT_REWARD = 4121
	-- GC_GET_MAP_PERFECT_REWARD
	MessageType.GC_GET_MAP_PERFECT_REWARD = 4122
	-- GC_UPDATE_PERFECT_REWARD_STATE
	MessageType.GC_UPDATE_PERFECT_REWARD_STATE = 4123
	-- GC_CLICK_STAGE
	MessageType.GC_CLICK_STAGE = 4124
	-- CG_ENTER_MAP_STRONGHOLD
	MessageType.CG_ENTER_MAP_STRONGHOLD = 4125
	-- GC_ENTER_MAP_STRONGHOLD
	MessageType.GC_ENTER_MAP_STRONGHOLD = 4126
	-- CG_CLICK_UNPERFECT_STAGE
	MessageType.CG_CLICK_UNPERFECT_STAGE = 4127
	-- GC_CLICK_UNPERFECT_STAGE
	MessageType.GC_CLICK_UNPERFECT_STAGE = 4128
	-- CG_VIP_SHOW_PANNEL
	MessageType.CG_VIP_SHOW_PANNEL = 4151
	-- GC_VIP_SHOW_PANNEL
	MessageType.GC_VIP_SHOW_PANNEL = 4152
	-- CG_SHOW_VIP_INFO
	MessageType.CG_SHOW_VIP_INFO = 4153
	-- GC_SHOW_VIP_INFO
	MessageType.GC_SHOW_VIP_INFO = 4154
	-- GC_DISPATCH_VIP_INFO
	MessageType.GC_DISPATCH_VIP_INFO = 4155
	-- CG_SHOW_CHARGE_ACTIVITY
	MessageType.CG_SHOW_CHARGE_ACTIVITY = 4156
	-- GC_SHOW_CHARGE_ACTIVITY
	MessageType.GC_SHOW_CHARGE_ACTIVITY = 4157
	-- GC_UPDATE_REVENUE_RATE_REQUEST
	MessageType.GC_UPDATE_REVENUE_RATE_REQUEST = 4201
	-- CG_UPDATE_REVENUE_RATE_RESPONSE
	MessageType.CG_UPDATE_REVENUE_RATE_RESPONSE = 4202
	-- CG_OPEN_QUESTION_PANNEL
	MessageType.CG_OPEN_QUESTION_PANNEL = 4251
	-- GC_UPDATE_QUESTION_PANNEL
	MessageType.GC_UPDATE_QUESTION_PANNEL = 4252
	-- CG_ANSWER_SUBMIT
	MessageType.CG_ANSWER_SUBMIT = 4253
	-- GC_ANSWER_UPDATE
	MessageType.GC_ANSWER_UPDATE = 4254
	-- CG_EXCHANGE_SCORE
	MessageType.CG_EXCHANGE_SCORE = 4255
	-- GC_EXCHANGE_SCORE
	MessageType.GC_EXCHANGE_SCORE = 4256
	-- GC_BUY_BLESS_COST
	MessageType.GC_BUY_BLESS_COST = 4257
	-- GC_UPDATE_SCORE_EXCHANGE_PANEL
	MessageType.GC_UPDATE_SCORE_EXCHANGE_PANEL = 4258
	-- CG_ONEKEY_ANSWER_QUESTION
	MessageType.CG_ONEKEY_ANSWER_QUESTION = 3074
	-- CG_UPDATE_COST_NOTIFY
	MessageType.CG_UPDATE_COST_NOTIFY = 4301
	-- GC_UPDATE_COST_NOTIFY
	MessageType.GC_UPDATE_COST_NOTIFY = 4302
	-- CG_OPEN_ARENA_PANEL
	MessageType.CG_OPEN_ARENA_PANEL = 4351
	-- GC_OPEN_ARENA_PANEL
	MessageType.GC_OPEN_ARENA_PANEL = 4352
	-- CG_VIEW_ARENA_RANK_REWARD_INFO
	MessageType.CG_VIEW_ARENA_RANK_REWARD_INFO = 4353
	-- GC_VIEW_ARENA_RANK_REWARD_INFO
	MessageType.GC_VIEW_ARENA_RANK_REWARD_INFO = 4354
	-- CG_GET_ARENA_RANK_REWARD
	MessageType.CG_GET_ARENA_RANK_REWARD = 4355
	-- GC_GET_ARENA_RANK_REWARD
	MessageType.GC_GET_ARENA_RANK_REWARD = 4356
	-- CG_ADD_ARENA_BATTLE_TIME
	MessageType.CG_ADD_ARENA_BATTLE_TIME = 4357
	-- GC_ADD_ARENA_BATTLE_TIME
	MessageType.GC_ADD_ARENA_BATTLE_TIME = 4358
	-- CG_SHOW_ARENA_RANK_LIST
	MessageType.CG_SHOW_ARENA_RANK_LIST = 4359
	-- GC_SHOW_ARENA_RANK_LIST
	MessageType.GC_SHOW_ARENA_RANK_LIST = 4360
	-- CG_ATTACK_ARENA_MEMBER
	MessageType.CG_ATTACK_ARENA_MEMBER = 4361
	-- GC_ATTACK_ARENA_MEMBER
	MessageType.GC_ATTACK_ARENA_MEMBER = 4362
	-- CG_EXPEDITE_BUY
	MessageType.CG_EXPEDITE_BUY = 4401
	-- GC_EXPEDITE_BUY
	MessageType.GC_EXPEDITE_BUY = 4402
	-- CG_UPDATE_MEDITATION_PANNEL
	MessageType.CG_UPDATE_MEDITATION_PANNEL = 4451
	-- GC_UPDATE_MEDITATION_PANNEL
	MessageType.GC_UPDATE_MEDITATION_PANNEL = 4452
	-- GC_UPDATE_MEDITATION_ASSIST_POSITION
	MessageType.GC_UPDATE_MEDITATION_ASSIST_POSITION = 4453
	-- CG_ASSIST_MEDITATION_APPLY
	MessageType.CG_ASSIST_MEDITATION_APPLY = 4454
	-- GC_ASSIST_MEDITATION_APPLY
	MessageType.GC_ASSIST_MEDITATION_APPLY = 4455
	-- CG_DEAL_ASSIST_MEDITATION_APPLY
	MessageType.CG_DEAL_ASSIST_MEDITATION_APPLY = 4456
	-- CG_QUERY_OPEN_ASSIST_POSITION_PRICE
	MessageType.CG_QUERY_OPEN_ASSIST_POSITION_PRICE = 4457
	-- GC_OPEN_ASSIST_POSITION_PRICE
	MessageType.GC_OPEN_ASSIST_POSITION_PRICE = 4458
	-- CG_OPEN_ASSIST_POSITION
	MessageType.CG_OPEN_ASSIST_POSITION = 4459
	-- GC_OPEN_ASSIST_POSITION
	MessageType.GC_OPEN_ASSIST_POSITION = 4460
	-- CG_START_MEDITATION
	MessageType.CG_START_MEDITATION = 4461
	-- CG_ABORT_MEDITATION
	MessageType.CG_ABORT_MEDITATION = 4462
	-- GC_MEDITATION_COMPLETE
	MessageType.GC_MEDITATION_COMPLETE = 4463
	-- GC_FRIEND_FOR_ASSIST_NOT_ENOUGH
	MessageType.GC_FRIEND_FOR_ASSIST_NOT_ENOUGH = 4464
	-- CG_QUERY_MEDITATION_POINT
	MessageType.CG_QUERY_MEDITATION_POINT = 4465
	-- GC_QUERY_MEDITATION_POINT
	MessageType.GC_QUERY_MEDITATION_POINT = 4466
	-- GC_START_MEDITATION
	MessageType.GC_START_MEDITATION = 4467
	-- GC_UPDATE_MEDITATION_STATE
	MessageType.GC_UPDATE_MEDITATION_STATE = 4468
	-- CG_TOTAL_MEDITATION_POINT
	MessageType.CG_TOTAL_MEDITATION_POINT = 4469
	-- GC_JOIN_BOSS_WAR
	MessageType.GC_JOIN_BOSS_WAR = 4501
	-- CG_ENCOURAGE_BOSS_WAR
	MessageType.CG_ENCOURAGE_BOSS_WAR = 4502
	-- GC_ENCOURAGE_BOSS_WAR
	MessageType.GC_ENCOURAGE_BOSS_WAR = 4503
	-- CG_CHARGED_BOSS_WAR
	MessageType.CG_CHARGED_BOSS_WAR = 4504
	-- GC_CHARGED_BOSS_WAR
	MessageType.GC_CHARGED_BOSS_WAR = 4505
	-- CG_CHARGED_BOSS
	MessageType.CG_CHARGED_BOSS = 4506
	-- CG_ATTACK_BOSS
	MessageType.CG_ATTACK_BOSS = 4507
	-- CG_GET_BOSS_REWARD
	MessageType.CG_GET_BOSS_REWARD = 4508
	-- GC_GET_BOSS_REWARD
	MessageType.GC_GET_BOSS_REWARD = 4509
	-- GC_HAS_BOSS_REWARD
	MessageType.GC_HAS_BOSS_REWARD = 4510
	-- CG_ENTER_BOSS_WAR
	MessageType.CG_ENTER_BOSS_WAR = 4511
	-- GC_CHARGED_BOSS
	MessageType.GC_CHARGED_BOSS = 4512
	-- CG_ENTER_ELITE_STAGE
	MessageType.CG_ENTER_ELITE_STAGE = 4551
	-- GC_ENTER_ELITE_STAGE
	MessageType.GC_ENTER_ELITE_STAGE = 4552
	-- GC_ELITE_STAGE_TYPE_LIST
	MessageType.GC_ELITE_STAGE_TYPE_LIST = 4553
	-- CG_ATTACK_ELITE_STAGE_BATTLE
	MessageType.CG_ATTACK_ELITE_STAGE_BATTLE = 4554
	-- GC_ATTACK_ELITE_STAGE_WARNING
	MessageType.GC_ATTACK_ELITE_STAGE_WARNING = 4555
	-- GC_ELITE_STAGE_BATTLE_RESULT
	MessageType.GC_ELITE_STAGE_BATTLE_RESULT = 4556
	-- GC_NEW_ELITE_STAGE_TYPE_OPEN
	MessageType.GC_NEW_ELITE_STAGE_TYPE_OPEN = 4557
	-- GC_UPDATE_ELITE_STAGE_CHALLENGE_COUNTER
	MessageType.GC_UPDATE_ELITE_STAGE_CHALLENGE_COUNTER = 4558
	-- CG_REFRESH_ELITE_STAGE_CHALLENGE_STATE
	MessageType.CG_REFRESH_ELITE_STAGE_CHALLENGE_STATE = 4559
	-- GC_UPDATE_ELITE_STAGE_CHALLENGE_STATE
	MessageType.GC_UPDATE_ELITE_STAGE_CHALLENGE_STATE = 4560
	-- CG_OPEN_ELITE_STAGE_PANEL
	MessageType.CG_OPEN_ELITE_STAGE_PANEL = 4561
	-- GC_OPEN_ELITE_STAGE_PANEL
	MessageType.GC_OPEN_ELITE_STAGE_PANEL = 4562
	-- CG_QUERY_ACTIVITY_LIST
	MessageType.CG_QUERY_ACTIVITY_LIST = 4601
	-- GC_ACTIVITY_LIST
	MessageType.GC_ACTIVITY_LIST = 4602
	-- GC_ALONE_ACTIVITY_LIST
	MessageType.GC_ALONE_ACTIVITY_LIST = 4603
	-- CG_ENTER_ACTIVITY
	MessageType.CG_ENTER_ACTIVITY = 4604
	-- GC_UPDATE_ACTIVITY_STATE
	MessageType.GC_UPDATE_ACTIVITY_STATE = 4605
	-- CG_SUBMIT_QUESTION
	MessageType.CG_SUBMIT_QUESTION = 4651
	-- CG_SHOW_QUESTIONS
	MessageType.CG_SHOW_QUESTIONS = 4652
	-- GC_SHOW_QUESTIONS
	MessageType.GC_SHOW_QUESTIONS = 4653
	-- CG_GET_COMMON_REWARD
	MessageType.CG_GET_COMMON_REWARD = 4701
	-- GC_REMOVE_COMMON_REWARD
	MessageType.GC_REMOVE_COMMON_REWARD = 4702
	-- GC_ADD_COMMON_REWARD
	MessageType.GC_ADD_COMMON_REWARD = 4703
	-- CG_UPDATE_MINE_PANNEL
	MessageType.CG_UPDATE_MINE_PANNEL = 4751
	-- GC_UPDATE_MINE_PANNEL
	MessageType.GC_UPDATE_MINE_PANNEL = 4752
	-- CG_OPEN_MINE_FIELD
	MessageType.CG_OPEN_MINE_FIELD = 4753
	-- GC_OPEN_MINE_FIELD
	MessageType.GC_OPEN_MINE_FIELD = 4754
	-- GC_OPEN_MINE_FIELD_BATTLE_REQUEST
	MessageType.GC_OPEN_MINE_FIELD_BATTLE_REQUEST = 4755
	-- CG_OPEN_MINE_FIELD_BATTLE_RESPONSE
	MessageType.CG_OPEN_MINE_FIELD_BATTLE_RESPONSE = 4756
	-- CG_MINE_HARVEST
	MessageType.CG_MINE_HARVEST = 4757
	-- GC_MINE_HARVEST
	MessageType.GC_MINE_HARVEST = 4758
	-- CG_BUY_MINE_TIMES
	MessageType.CG_BUY_MINE_TIMES = 4759
	-- GC_BUY_MINE_TIMES
	MessageType.GC_BUY_MINE_TIMES = 4760
	-- CG_RESET_MINE_FIELD
	MessageType.CG_RESET_MINE_FIELD = 4761
	-- GC_RESET_MINE_FIELD
	MessageType.GC_RESET_MINE_FIELD = 4762
	-- GC_MINE_FIELD_LIST
	MessageType.GC_MINE_FIELD_LIST = 4763
	-- CG_SHOW_HELP_INFOS
	MessageType.CG_SHOW_HELP_INFOS = 4801
	-- GC_SHOW_HELP_INFOS
	MessageType.GC_SHOW_HELP_INFOS = 4802
	-- CG_SHOW_ELITE_STAGE_AUTO_BATTLE_PANEL
	MessageType.CG_SHOW_ELITE_STAGE_AUTO_BATTLE_PANEL = 4851
	-- GC_SHOW_ELITE_STAGE_AUTO_BATTLE_PANEL
	MessageType.GC_SHOW_ELITE_STAGE_AUTO_BATTLE_PANEL = 4852
	-- CG_START_ELITE_AUTO_BATTLE
	MessageType.CG_START_ELITE_AUTO_BATTLE = 4853
	-- CG_CANCEL_ELITE_AUTO_BATTLE
	MessageType.CG_CANCEL_ELITE_AUTO_BATTLE = 4854
	-- GC_ELITE_AUTO_BATTLE_STATE
	MessageType.GC_ELITE_AUTO_BATTLE_STATE = 4855
	-- GC_ELITE_AUTO_BATTLE_RESULT
	MessageType.GC_ELITE_AUTO_BATTLE_RESULT = 4856
	-- CG_SHOW_STAGE_AUTO_BATTLE_PANEL
	MessageType.CG_SHOW_STAGE_AUTO_BATTLE_PANEL = 4857
	-- GC_SHOW_STAGE_AUTO_BATTLE_PANEL
	MessageType.GC_SHOW_STAGE_AUTO_BATTLE_PANEL = 4858
	-- CG_START_STAGE_AUTO_BATTLE
	MessageType.CG_START_STAGE_AUTO_BATTLE = 4859
	-- CG_CANCEL_STAGE_AUTO_BATTLE
	MessageType.CG_CANCEL_STAGE_AUTO_BATTLE = 4860
	-- GC_STAGE_AUTO_BATTLE_STATE
	MessageType.GC_STAGE_AUTO_BATTLE_STATE = 4861
	-- GC_STAGE_AUTO_BATTLE_RESULT
	MessageType.GC_STAGE_AUTO_BATTLE_RESULT = 4862
	-- CG_SHOW_HONOUR_SHOP_ITEM_LIST
	MessageType.CG_SHOW_HONOUR_SHOP_ITEM_LIST = 4901
	-- GC_SHOW_HONOUR_SHOP_ITEM_LIST
	MessageType.GC_SHOW_HONOUR_SHOP_ITEM_LIST = 4902
	-- CG_BUY_HONOUR_SHOP_ITEM
	MessageType.CG_BUY_HONOUR_SHOP_ITEM = 4903
	-- GC_BUY_HONOUR_SHOP_ITEM
	MessageType.GC_BUY_HONOUR_SHOP_ITEM = 4904
	-- CG_SHOW_GIFT_PANEL
	MessageType.CG_SHOW_GIFT_PANEL = 4951
	-- GC_SHOW_GIFT_PANEL
	MessageType.GC_SHOW_GIFT_PANEL = 4952
	-- CG_ACTIVE_GIFT
	MessageType.CG_ACTIVE_GIFT = 4953
	-- GC_UPDATE_GIFT_STATE
	MessageType.GC_UPDATE_GIFT_STATE = 4954
	-- CG_RESET_GIFT
	MessageType.CG_RESET_GIFT = 4955
	-- GC_UPDATE_GIFT_ACTIVE_NOTICE_STATE
	MessageType.GC_UPDATE_GIFT_ACTIVE_NOTICE_STATE = 4956
	-- CG_UPGRADE_GIFT
	MessageType.CG_UPGRADE_GIFT = 4957
	-- CG_SHOW_FOSTER_PANEL
	MessageType.CG_SHOW_FOSTER_PANEL = 5001
	-- GC_SHOW_FOSTER_PANEL
	MessageType.GC_SHOW_FOSTER_PANEL = 5002
	-- CG_FOSTER
	MessageType.CG_FOSTER = 5003
	-- GC_FOSTER
	MessageType.GC_FOSTER = 5004
	-- CG_SAVE_FOSTER
	MessageType.CG_SAVE_FOSTER = 5005
	-- GC_SAVE_FOSTER
	MessageType.GC_SAVE_FOSTER = 5006
	-- CG_SELECT_EQUIP_TO_FORGE
	MessageType.CG_SELECT_EQUIP_TO_FORGE = 5051
	-- GC_SELECT_EQUIP_TO_FORGE
	MessageType.GC_SELECT_EQUIP_TO_FORGE = 5052
	-- CG_EQUIP_FORGE_TO_LOCK
	MessageType.CG_EQUIP_FORGE_TO_LOCK = 5053
	-- GC_EQUIP_FORGE_TO_LOCK
	MessageType.GC_EQUIP_FORGE_TO_LOCK = 5054
	-- CG_EQUIP_FORGE
	MessageType.CG_EQUIP_FORGE = 5055
	-- GC_UPDATE_EQUIP_FORGE_PANEL
	MessageType.GC_UPDATE_EQUIP_FORGE_PANEL = 5056
	-- CG_EQUIP_FORGE_REPLACE
	MessageType.CG_EQUIP_FORGE_REPLACE = 5057
	-- GC_EQUIP_FORGE_REPLACE
	MessageType.GC_EQUIP_FORGE_REPLACE = 5058
	-- CG_EQUIP_FORGE_CANCEL
	MessageType.CG_EQUIP_FORGE_CANCEL = 5059
	-- GC_EQUIP_FORGE_CANCEL
	MessageType.GC_EQUIP_FORGE_CANCEL = 5060
	-- CG_OPEN_REFINE_PANEL
	MessageType.CG_OPEN_REFINE_PANEL = 5101
	-- GC_OPEN_REFINE_PANEL
	MessageType.GC_OPEN_REFINE_PANEL = 5102
	-- CG_ATTACK_REFINE_STAGE
	MessageType.CG_ATTACK_REFINE_STAGE = 5103
	-- CG_AUTO_ATTACK_REFINE_STAGE
	MessageType.CG_AUTO_ATTACK_REFINE_STAGE = 5104
	-- CG_ATTACK_ALL_REFINE_STAGE
	MessageType.CG_ATTACK_ALL_REFINE_STAGE = 5105
	-- CG_REFRESH_REFINE_MAP
	MessageType.CG_REFRESH_REFINE_MAP = 5106
	-- GC_ATTACK_REFINE_STAGE
	MessageType.GC_ATTACK_REFINE_STAGE = 5107
	-- GC_ATTACK_REFINE_STAGE_FIRST
	MessageType.GC_ATTACK_REFINE_STAGE_FIRST = 5108
	-- GC_REFINE_BAG_FULL
	MessageType.GC_REFINE_BAG_FULL = 5109
	-- GC_UPDATE_REFINE_PANEL
	MessageType.GC_UPDATE_REFINE_PANEL = 5110
	-- GC_JOIN_MATCH_BATTLE_SCENE
	MessageType.GC_JOIN_MATCH_BATTLE_SCENE = 5151
	-- CG_ENCOURAGE_MATCH_BATTLE
	MessageType.CG_ENCOURAGE_MATCH_BATTLE = 5152
	-- GC_ENCOURAGE_MATCH_BATTLE
	MessageType.GC_ENCOURAGE_MATCH_BATTLE = 5153
	-- GC_BATTLE_REPORT
	MessageType.GC_BATTLE_REPORT = 5154
	-- GC_UPDATE_MATCH_BATTLE_RANK
	MessageType.GC_UPDATE_MATCH_BATTLE_RANK = 5155
	-- CG_READY_FOR_MATCH_BATTLE
	MessageType.CG_READY_FOR_MATCH_BATTLE = 5156
	-- CG_UPDATE_AUTO_MATCH_BATTLE_SETTING
	MessageType.CG_UPDATE_AUTO_MATCH_BATTLE_SETTING = 5157
	-- GC_UPDATE_MATCH_BATTLE_ROLE
	MessageType.GC_UPDATE_MATCH_BATTLE_ROLE = 5158
	-- CG_LEAVE_MATCH_BATTLE_SCENE
	MessageType.CG_LEAVE_MATCH_BATTLE_SCENE = 5159
	-- CG_CANCEL_READY_FOR_MATCH_BATTLE
	MessageType.CG_CANCEL_READY_FOR_MATCH_BATTLE = 5160
	-- GC_ADD_MATCH_BATTLE_ROLE
	MessageType.GC_ADD_MATCH_BATTLE_ROLE = 5161
	-- GC_REMOVE_MATCH_BATTLE_ROLE
	MessageType.GC_REMOVE_MATCH_BATTLE_ROLE = 5162
	-- GC_UPDATE_MATCH_BATTLE_RESULT
	MessageType.GC_UPDATE_MATCH_BATTLE_RESULT = 5163
	-- GC_UPDATE_AUTO_MATCH_BATTLE_SETTING
	MessageType.GC_UPDATE_AUTO_MATCH_BATTLE_SETTING = 5164
	-- CG_JOIN_MATCH_BATTLE_SCENE
	MessageType.CG_JOIN_MATCH_BATTLE_SCENE = 5165
	-- CG_OPEN_FUNC_HELP_PANEL
	MessageType.CG_OPEN_FUNC_HELP_PANEL = 5201
	-- GC_OPEN_FUNC_HELP_PANEL
	MessageType.GC_OPEN_FUNC_HELP_PANEL = 5202
	-- CG_SHOW_FUNC_HELP_INFOS
	MessageType.CG_SHOW_FUNC_HELP_INFOS = 5203
	-- GC_SHOW_FUNC_HELP_INFOS
	MessageType.GC_SHOW_FUNC_HELP_INFOS = 5204
	-- CG_OPEN_WARRIOR_WAY_PANEL
	MessageType.CG_OPEN_WARRIOR_WAY_PANEL = 5251
	-- GC_OPEN_WARRIOR_WAY_PANEL
	MessageType.GC_OPEN_WARRIOR_WAY_PANEL = 5252
	-- CG_REFRESH_OPPONENT
	MessageType.CG_REFRESH_OPPONENT = 5253
	-- GC_UPDATE_OPPONENT
	MessageType.GC_UPDATE_OPPONENT = 5254
	-- CG_START_WARRIOR_BATTLE_REQUEST
	MessageType.CG_START_WARRIOR_BATTLE_REQUEST = 5255
	-- GC_UPDATE_WARRIOR_QUEST
	MessageType.GC_UPDATE_WARRIOR_QUEST = 5256
	-- CG_GET_WARRIOR_QUEST_REWARD
	MessageType.CG_GET_WARRIOR_QUEST_REWARD = 5257
	-- GC_GET_WARRIOR_QUEST_REWARD
	MessageType.GC_GET_WARRIOR_QUEST_REWARD = 5258
	-- GC_UPDATE_WARRIOR_QUEST_REWARD_STATE
	MessageType.GC_UPDATE_WARRIOR_QUEST_REWARD_STATE = 5259
	-- GC_JOIN_WARRIOR_BATTLE_REQUEST
	MessageType.GC_JOIN_WARRIOR_BATTLE_REQUEST = 5260
	-- GC_WARRIOR_STATE
	MessageType.GC_WARRIOR_STATE = 5261
	-- GC_BATTLE_GUIDE_CHESSBOARD
	MessageType.GC_BATTLE_GUIDE_CHESSBOARD = 5301
	-- GC_BATTLE_GUIDE_FOUR_BOMBS
	MessageType.GC_BATTLE_GUIDE_FOUR_BOMBS = 5302
	-- GC_BATTLE_GUIDE_THREE_BOMBS
	MessageType.GC_BATTLE_GUIDE_THREE_BOMBS = 5303
	-- GC_BATTLE_GUIDE_USE_SKILL
	MessageType.GC_BATTLE_GUIDE_USE_SKILL = 5304
	-- GC_BATTLE_GUIDE_SKILL_INFO
	MessageType.GC_BATTLE_GUIDE_SKILL_INFO = 5305
	-- CG_OPEN_YELLOW_VIP_REWARD_PANEL
	MessageType.CG_OPEN_YELLOW_VIP_REWARD_PANEL = 5351
	-- GC_OPEN_YELLOW_VIP_REWARD_PANEL
	MessageType.GC_OPEN_YELLOW_VIP_REWARD_PANEL = 5352
	-- CG_RECEIVE_YELLOW_VIP_REWARD
	MessageType.CG_RECEIVE_YELLOW_VIP_REWARD = 5353
	-- GC_UPDATE_YELLOW_VIP_REWARD_STATE
	MessageType.GC_UPDATE_YELLOW_VIP_REWARD_STATE = 5354
	-- CG_RECEIVE_YELLOW_VIP_LEVEL_UP_REWARD
	MessageType.CG_RECEIVE_YELLOW_VIP_LEVEL_UP_REWARD = 5355
	-- CG_SHOW_RECHARGE_PANEL
	MessageType.CG_SHOW_RECHARGE_PANEL = 5401
	-- GC_SHOW_RECHARGE_PANEL
	MessageType.GC_SHOW_RECHARGE_PANEL = 5402
	-- CG_RECHARGE
	MessageType.CG_RECHARGE = 5403
	-- GC_RECHARGE
	MessageType.GC_RECHARGE = 5404
	-- GC_RECHARGE_FINISHED
	MessageType.GC_RECHARGE_FINISHED = 5405
	-- CG_OPEN_TITLE_PANEL
	MessageType.CG_OPEN_TITLE_PANEL = 5451
	-- GC_OPEN_TITLE_PANEL
	MessageType.GC_OPEN_TITLE_PANEL = 5452
	-- CG_TITLE_LEVEL_UP
	MessageType.CG_TITLE_LEVEL_UP = 5453
	-- GC_TITLE_LEVEL_UP
	MessageType.GC_TITLE_LEVEL_UP = 5454
	-- CG_GET_TITLE_SALARY
	MessageType.CG_GET_TITLE_SALARY = 5455
	-- GC_GET_TITLE_SALARY
	MessageType.GC_GET_TITLE_SALARY = 5456
	-- CG_OPEN_LEGION_PANEL
	MessageType.CG_OPEN_LEGION_PANEL = 5501
	-- GC_OPEN_LEGION_PANEL
	MessageType.GC_OPEN_LEGION_PANEL = 5502
	-- CG_SHOW_LEGION_LIST_TAB
	MessageType.CG_SHOW_LEGION_LIST_TAB = 5503
	-- GC_SHOW_LEGION_LIST_TAB
	MessageType.GC_SHOW_LEGION_LIST_TAB = 5504
	-- CG_SHOW_LEGION_INFO_TAB
	MessageType.CG_SHOW_LEGION_INFO_TAB = 5505
	-- GC_SHOW_LEGION_INFO_TAB
	MessageType.GC_SHOW_LEGION_INFO_TAB = 5506
	-- CG_SHOW_LEGION_MEMBER_TAB
	MessageType.CG_SHOW_LEGION_MEMBER_TAB = 5507
	-- GC_SHOW_LEGION_MEMBER_TAB
	MessageType.GC_SHOW_LEGION_MEMBER_TAB = 5508
	-- CG_SHOW_LEGION_LOG_TAB
	MessageType.CG_SHOW_LEGION_LOG_TAB = 5509
	-- GC_SHOW_LEGION_LOG_TAB
	MessageType.GC_SHOW_LEGION_LOG_TAB = 5510
	-- CG_SHOW_LEGION_APPLY_TAB
	MessageType.CG_SHOW_LEGION_APPLY_TAB = 5511
	-- GC_SHOW_LEGION_APPLY_TAB
	MessageType.GC_SHOW_LEGION_APPLY_TAB = 5512
	-- CG_CREATE_LEGION
	MessageType.CG_CREATE_LEGION = 5513
	-- GC_CREATE_LEGION
	MessageType.GC_CREATE_LEGION = 5514
	-- CG_APPLY_JOIN_LEGION
	MessageType.CG_APPLY_JOIN_LEGION = 5515
	-- GC_APPLY_JOIN_LEGION
	MessageType.GC_APPLY_JOIN_LEGION = 5516
	-- CG_AGREE_JOIN_LEGION
	MessageType.CG_AGREE_JOIN_LEGION = 5517
	-- GC_AGREE_JOIN_LEGION
	MessageType.GC_AGREE_JOIN_LEGION = 5518
	-- CG_REJECT_JOIN_LEGION
	MessageType.CG_REJECT_JOIN_LEGION = 5519
	-- GC_REJECT_JOIN_LEGION
	MessageType.GC_REJECT_JOIN_LEGION = 5520
	-- CG_QUIT_LEGION
	MessageType.CG_QUIT_LEGION = 5521
	-- GC_QUIT_LEGION
	MessageType.GC_QUIT_LEGION = 5522
	-- CG_DISSOLVE_LEGION
	MessageType.CG_DISSOLVE_LEGION = 5523
	-- GC_DISSOLVE_LEGION
	MessageType.GC_DISSOLVE_LEGION = 5524
	-- CG_REMOVE_LEGION_MEMBER
	MessageType.CG_REMOVE_LEGION_MEMBER = 5525
	-- GC_REMOVE_LEGION_MEMBER
	MessageType.GC_REMOVE_LEGION_MEMBER = 5526
	-- CG_APPLY_LEGION_COMMANDER
	MessageType.CG_APPLY_LEGION_COMMANDER = 5527
	-- GC_APPLY_LEGION_COMMANDER
	MessageType.GC_APPLY_LEGION_COMMANDER = 5528
	-- CG_TRANSFER_LEGION
	MessageType.CG_TRANSFER_LEGION = 5529
	-- GC_TRANSFER_LEGION
	MessageType.GC_TRANSFER_LEGION = 5530
	-- CG_SEARCH_LEGION
	MessageType.CG_SEARCH_LEGION = 5531
	-- GC_SEARCH_LEGION
	MessageType.GC_SEARCH_LEGION = 5532
	-- CG_ADD_LEGION_NOTICE
	MessageType.CG_ADD_LEGION_NOTICE = 5533
	-- GC_ADD_LEGION_NOTICE
	MessageType.GC_ADD_LEGION_NOTICE = 5534
	-- GC_UPDATE_HUMAN_LEGION_INFO
	MessageType.GC_UPDATE_HUMAN_LEGION_INFO = 5535
	-- CG_UPGRADE_LEGION_BUILDING
	MessageType.CG_UPGRADE_LEGION_BUILDING = 5536
	-- GC_UPGRADE_LEGION_BUILDING
	MessageType.GC_UPGRADE_LEGION_BUILDING = 5537
	-- CG_SHOW_LEGION_MEDITATION_TAB
	MessageType.CG_SHOW_LEGION_MEDITATION_TAB = 5538
	-- GC_SHOW_LEGION_MEDITATION_TAB
	MessageType.GC_SHOW_LEGION_MEDITATION_TAB = 5539
	-- CG_LEGION_MEDITATION
	MessageType.CG_LEGION_MEDITATION = 5540
	-- GC_LEGION_MEDITATION
	MessageType.GC_LEGION_MEDITATION = 5541
	-- CG_SHOW_LEGION_SHOP_TAB
	MessageType.CG_SHOW_LEGION_SHOP_TAB = 5542
	-- GC_SHOW_LEGION_SHOP_TAB
	MessageType.GC_SHOW_LEGION_SHOP_TAB = 5543
	-- CG_SHOW_LEGION_SHOP_ITEMS
	MessageType.CG_SHOW_LEGION_SHOP_ITEMS = 5544
	-- GC_SHOW_LEGION_SHOP_ITEMS
	MessageType.GC_SHOW_LEGION_SHOP_ITEMS = 5545
	-- CG_BUY_LEGION_SHOP_ITEM
	MessageType.CG_BUY_LEGION_SHOP_ITEM = 5546
	-- GC_BUY_LEGION_SHOP_ITEM
	MessageType.GC_BUY_LEGION_SHOP_ITEM = 5547
	-- CG_SHOW_LEGION_HONOR_TAB
	MessageType.CG_SHOW_LEGION_HONOR_TAB = 5548
	-- GC_SHOW_LEGION_HONOR_TAB
	MessageType.GC_SHOW_LEGION_HONOR_TAB = 5549
	-- CG_EXCHANGE_LEGION_TITLE
	MessageType.CG_EXCHANGE_LEGION_TITLE = 5550
	-- GC_EXCHANGE_LEGION_TITLE
	MessageType.GC_EXCHANGE_LEGION_TITLE = 5551
	-- CG_SHOW_LEGION_TECHNOLOGY_TAB
	MessageType.CG_SHOW_LEGION_TECHNOLOGY_TAB = 5552
	-- GC_SHOW_LEGION_TECHNOLOGY_TAB
	MessageType.GC_SHOW_LEGION_TECHNOLOGY_TAB = 5553
	-- CG_CONTRIBUTE_LEGION_TECHNOLOGY
	MessageType.CG_CONTRIBUTE_LEGION_TECHNOLOGY = 5554
	-- GC_CONTRIBUTE_LEGION_TECHNOLOGY
	MessageType.GC_CONTRIBUTE_LEGION_TECHNOLOGY = 5555
	-- CG_SHOW_LEGION_TASK_TAB
	MessageType.CG_SHOW_LEGION_TASK_TAB = 5556
	-- GC_SHOW_LEGION_TASK_TAB
	MessageType.GC_SHOW_LEGION_TASK_TAB = 5557
	-- CG_REFRESH_LEGION_TASK_LIST
	MessageType.CG_REFRESH_LEGION_TASK_LIST = 5558
	-- GC_REFRESH_LEGION_TASK_LIST
	MessageType.GC_REFRESH_LEGION_TASK_LIST = 5559
	-- CG_START_LEGION_TASK
	MessageType.CG_START_LEGION_TASK = 5560
	-- GC_START_LEGION_TASK
	MessageType.GC_START_LEGION_TASK = 5561
	-- CG_ABORT_LEGION_TASK
	MessageType.CG_ABORT_LEGION_TASK = 5562
	-- GC_ABORT_LEGION_TASK
	MessageType.GC_ABORT_LEGION_TASK = 5563
	-- CG_COMPLETE_LEGION_TASK
	MessageType.CG_COMPLETE_LEGION_TASK = 5564
	-- GC_COMPLETE_LEGION_TASK
	MessageType.GC_COMPLETE_LEGION_TASK = 5565
	-- CG_APPLY_COMPLETE_LEGION_TASK
	MessageType.CG_APPLY_COMPLETE_LEGION_TASK = 5566
	-- GC_APPLY_COMPLETE_LEGION_TASK
	MessageType.GC_APPLY_COMPLETE_LEGION_TASK = 5567
	-- CG_GET_LEGION_TASK_REWARD
	MessageType.CG_GET_LEGION_TASK_REWARD = 5568
	-- GC_GET_LEGION_TASK_REWARD
	MessageType.GC_GET_LEGION_TASK_REWARD = 5569
	-- CG_SHOW_LEGION_TASK_RANK
	MessageType.CG_SHOW_LEGION_TASK_RANK = 5570
	-- GC_SHOW_LEGION_TASK_RANK
	MessageType.GC_SHOW_LEGION_TASK_RANK = 5571
	-- CG_GET_LEGION_TASK_RANK_REWARD
	MessageType.CG_GET_LEGION_TASK_RANK_REWARD = 5572
	-- GC_GET_LEGION_TASK_RANK_REWARD
	MessageType.GC_GET_LEGION_TASK_RANK_REWARD = 5573
	-- GC_SEND_HUMAN_LEGION_TITLE_INFO
	MessageType.GC_SEND_HUMAN_LEGION_TITLE_INFO = 5574
	-- CG_SHOW_LEGION_MINE_TAB
	MessageType.CG_SHOW_LEGION_MINE_TAB = 5575
	-- GC_SHOW_LEGION_MINE_TAB
	MessageType.GC_SHOW_LEGION_MINE_TAB = 5576
	-- CG_DONATE_LEGION_CRYSTAL
	MessageType.CG_DONATE_LEGION_CRYSTAL = 5577
	-- GC_DONATE_LEGION_CRYSTAL
	MessageType.GC_DONATE_LEGION_CRYSTAL = 5578
	-- CG_OPEN_GODSOUL_PANEL
	MessageType.CG_OPEN_GODSOUL_PANEL = 5851
	-- GC_OPEN_GODSOUL_PANEL
	MessageType.GC_OPEN_GODSOUL_PANEL = 5852
	-- CG_UPGRADE_EQUIP_BIT
	MessageType.CG_UPGRADE_EQUIP_BIT = 5853
	-- GC_UPGRADE_EQUIP_BIT
	MessageType.GC_UPGRADE_EQUIP_BIT = 5854
	-- CG_SHOW_MAGIC_PAPER_TAB
	MessageType.CG_SHOW_MAGIC_PAPER_TAB = 5855
	-- GC_SHOW_MAGIC_PAPER_TAB
	MessageType.GC_SHOW_MAGIC_PAPER_TAB = 5856
	-- CG_UPGRADE_MAGIC_PAPER
	MessageType.CG_UPGRADE_MAGIC_PAPER = 5857
	-- GC_UPGRADE_MAGIC_PAPER
	MessageType.GC_UPGRADE_MAGIC_PAPER = 5858
	-- CG_OPEN_PRISON_PANEL
	MessageType.CG_OPEN_PRISON_PANEL = 6201
	-- GC_OPEN_PRISON_PANEL
	MessageType.GC_OPEN_PRISON_PANEL = 6202
	-- CG_SHOW_PRISON_LOG_TAB
	MessageType.CG_SHOW_PRISON_LOG_TAB = 6203
	-- GC_SHOW_PRISON_LOG_TAB
	MessageType.GC_SHOW_PRISON_LOG_TAB = 6204
	-- CG_SHOW_ARREST_TAB
	MessageType.CG_SHOW_ARREST_TAB = 6205
	-- GC_SHOW_ARREST_TAB
	MessageType.GC_SHOW_ARREST_TAB = 6206
	-- CG_SHOW_LOOSER_TAB
	MessageType.CG_SHOW_LOOSER_TAB = 6207
	-- GC_SHOW_LOOSER_TAB
	MessageType.GC_SHOW_LOOSER_TAB = 6208
	-- CG_SHOW_ENEMY_TAB
	MessageType.CG_SHOW_ENEMY_TAB = 6209
	-- GC_SHOW_ENEMY_TAB
	MessageType.GC_SHOW_ENEMY_TAB = 6210
	-- CG_APPLY_ARREST
	MessageType.CG_APPLY_ARREST = 6211
	-- GC_APPLY_ARREST
	MessageType.GC_APPLY_ARREST = 6212
	-- CG_BUY_ARREST_NUM
	MessageType.CG_BUY_ARREST_NUM = 6213
	-- GC_BUY_ARREST_NUM
	MessageType.GC_BUY_ARREST_NUM = 6214
	-- CG_SHOW_RESCUE_TAB
	MessageType.CG_SHOW_RESCUE_TAB = 6215
	-- GC_SHOW_RESCUE_TAB
	MessageType.GC_SHOW_RESCUE_TAB = 6216
	-- CG_APPLY_RESCUE
	MessageType.CG_APPLY_RESCUE = 6217
	-- GC_APPLY_RESCUE
	MessageType.GC_APPLY_RESCUE = 6218
	-- CG_SLAVE_SHOW_MASTER_TAB
	MessageType.CG_SLAVE_SHOW_MASTER_TAB = 6219
	-- GC_SLAVE_SHOW_MASTER_TAB
	MessageType.GC_SLAVE_SHOW_MASTER_TAB = 6220
	-- CG_SLAVE_INTERACT
	MessageType.CG_SLAVE_INTERACT = 6221
	-- GC_SLAVE_INTERACT
	MessageType.GC_SLAVE_INTERACT = 6222
	-- CG_SLAVE_REVOLT
	MessageType.CG_SLAVE_REVOLT = 6223
	-- GC_SLAVE_REVOLT
	MessageType.GC_SLAVE_REVOLT = 6224
	-- CG_SLAVE_SHOW_SOS_TAB
	MessageType.CG_SLAVE_SHOW_SOS_TAB = 6225
	-- GC_SLAVE_SHOW_SOS_TAB
	MessageType.GC_SLAVE_SHOW_SOS_TAB = 6226
	-- CG_SLAVE_FOR_HELP
	MessageType.CG_SLAVE_FOR_HELP = 6227
	-- GC_SLAVE_FOR_HELP
	MessageType.GC_SLAVE_FOR_HELP = 6228
	-- GC_SLAVE_FOR_HELPED
	MessageType.GC_SLAVE_FOR_HELPED = 6229
	-- CG_MASTER_GET_SLAVE_LIST
	MessageType.CG_MASTER_GET_SLAVE_LIST = 6230
	-- GC_MASTER_GET_SLAVE_LIST
	MessageType.GC_MASTER_GET_SLAVE_LIST = 6231
	-- CG_SHOW_PRESS_TAB
	MessageType.CG_SHOW_PRESS_TAB = 6232
	-- GC_SHOW_PRESS_TAB
	MessageType.GC_SHOW_PRESS_TAB = 6233
	-- CG_MASTER_APPLY_EXTRACT_EXPERIENCE
	MessageType.CG_MASTER_APPLY_EXTRACT_EXPERIENCE = 6234
	-- GC_MASTER_APPLY_EXTRACT_EXPERIENCE
	MessageType.GC_MASTER_APPLY_EXTRACT_EXPERIENCE = 6235
	-- CG_MASTER_EXTRACT_EXPERIENCE
	MessageType.CG_MASTER_EXTRACT_EXPERIENCE = 6236
	-- GC_MASTER_EXTRACT_EXPERIENCE
	MessageType.GC_MASTER_EXTRACT_EXPERIENCE = 6237
	-- CG_MASTER_RELEASE
	MessageType.CG_MASTER_RELEASE = 6238
	-- GC_MASTER_RELEASE
	MessageType.GC_MASTER_RELEASE = 6239
	-- CG_MASTER_INTERACT
	MessageType.CG_MASTER_INTERACT = 6240
	-- GC_MASTER_INTERACT
	MessageType.GC_MASTER_INTERACT = 6241
	-- GC_PRISON_IDENTITY_CHANGED
	MessageType.GC_PRISON_IDENTITY_CHANGED = 6242
	-- CG_OPEN_ABATTOIR_PANEL
	MessageType.CG_OPEN_ABATTOIR_PANEL = 6243
	-- GC_OPEN_ABATTOIR_PANEL
	MessageType.GC_OPEN_ABATTOIR_PANEL = 6244
	-- CG_LOOT_ABATTOIR_ROOM
	MessageType.CG_LOOT_ABATTOIR_ROOM = 6245
	-- CG_QUIT_ABATTOIR_ROOM
	MessageType.CG_QUIT_ABATTOIR_ROOM = 6246
	-- GC_QUIT_ABATTOIR_ROOM
	MessageType.GC_QUIT_ABATTOIR_ROOM = 6247
	-- CG_BUY_ABATTOIR_WRESTLE_NUM
	MessageType.CG_BUY_ABATTOIR_WRESTLE_NUM = 6248
	-- GC_BUY_ABATTOIR_WRESTLE_NUM
	MessageType.GC_BUY_ABATTOIR_WRESTLE_NUM = 6249
	-- CG_EXTRACT_ABATTOIR_HONOR
	MessageType.CG_EXTRACT_ABATTOIR_HONOR = 6250
	-- GC_EXTRACT_ABATTOIR_PRESTIGE
	MessageType.GC_EXTRACT_ABATTOIR_PRESTIGE = 6251
	-- CG_SHOW_ABATTOIR_ENEMY
	MessageType.CG_SHOW_ABATTOIR_ENEMY = 6252
	-- GC_SHOW_ABATTOIR_ENEMY
	MessageType.GC_SHOW_ABATTOIR_ENEMY = 6253
	-- CG_OPEN_BLOOD_TEMPLE_PANEL
	MessageType.CG_OPEN_BLOOD_TEMPLE_PANEL = 6301
	-- GC_OPEN_BLOOD_TEMPLE_PANEL
	MessageType.GC_OPEN_BLOOD_TEMPLE_PANEL = 6302
	-- CG_SHOW_BLOOD_TEMPLE_ROOM
	MessageType.CG_SHOW_BLOOD_TEMPLE_ROOM = 6303
	-- GC_SHOW_BLOOD_TEMPLE_ROOM
	MessageType.GC_SHOW_BLOOD_TEMPLE_ROOM = 6304
	-- CG_LOOT_BLOOD_TEMPLE_ROOM
	MessageType.CG_LOOT_BLOOD_TEMPLE_ROOM = 6305
	-- CG_QUIT_BLOOD_TEMPLE_ROOM
	MessageType.CG_QUIT_BLOOD_TEMPLE_ROOM = 6306
	-- GC_QUIT_BLOOD_TEMPLE_ROOM
	MessageType.GC_QUIT_BLOOD_TEMPLE_ROOM = 6307
	-- CG_BUY_BLOOD_TEMPLE_WRESTLE_NUM
	MessageType.CG_BUY_BLOOD_TEMPLE_WRESTLE_NUM = 6308
	-- GC_BUY_BLOOD_TEMPLE_WRESTLE_NUM
	MessageType.GC_BUY_BLOOD_TEMPLE_WRESTLE_NUM = 6309
	-- CG_EXTRACT_BLOOD_TEMPLE_HONOR
	MessageType.CG_EXTRACT_BLOOD_TEMPLE_HONOR = 6310
	-- GC_EXTRACT_BLOOD_TEMPLE_PRESTIGE
	MessageType.GC_EXTRACT_BLOOD_TEMPLE_PRESTIGE = 6311
	-- CG_SHOW_BLOOD_TEMPLE_ENEMY
	MessageType.CG_SHOW_BLOOD_TEMPLE_ENEMY = 6312
	-- GC_SHOW_BLOOD_TEMPLE_ENEMY
	MessageType.GC_SHOW_BLOOD_TEMPLE_ENEMY = 6313
	-- CG_OPEN_PUB_PANEL
	MessageType.CG_OPEN_PUB_PANEL = 6351
	-- GC_OPEN_PUB_PANEL
	MessageType.GC_OPEN_PUB_PANEL = 6352
	-- CG_FINGER_GUESSING
	MessageType.CG_FINGER_GUESSING = 6353
	-- GC_FINGER_GUESSING
	MessageType.GC_FINGER_GUESSING = 6354
	-- CG_GIVE_FINGER
	MessageType.CG_GIVE_FINGER = 6355
	-- GC_GIVE_FINGER
	MessageType.GC_GIVE_FINGER = 6356
	-- GC_PUB_PAGE_INFO
	MessageType.GC_PUB_PAGE_INFO = 6357
	-- CG_SUCCEED_FINGER
	MessageType.CG_SUCCEED_FINGER = 6358
	-- CG_OPEN_RECRUIT_PANEL
	MessageType.CG_OPEN_RECRUIT_PANEL = 6359
	-- GC_OPEN_RECRUIT_PANEL
	MessageType.GC_OPEN_RECRUIT_PANEL = 6360
	-- CG_RECRUIT_SPRITE
	MessageType.CG_RECRUIT_SPRITE = 6361
	-- GC_RECRUIT_SPRITE
	MessageType.GC_RECRUIT_SPRITE = 6362
	-- GC_RECRUIT_CONFIG
	MessageType.GC_RECRUIT_CONFIG = 6363
	-- CG_OPEN_SPRITE_PANEL
	MessageType.CG_OPEN_SPRITE_PANEL = 6364
	-- GC_OPEN_SPRITE_PANEL
	MessageType.GC_OPEN_SPRITE_PANEL = 6365
	-- CG_BUY_SPRITE_CELL
	MessageType.CG_BUY_SPRITE_CELL = 6366
	-- GC_BUY_SPRITE_CELL
	MessageType.GC_BUY_SPRITE_CELL = 6367
	-- CG_EQUIP_SPRITE
	MessageType.CG_EQUIP_SPRITE = 6368
	-- CG_UNEQUIP_SPRITE
	MessageType.CG_UNEQUIP_SPRITE = 6369
	-- GC_SPRITE_EQUIP_STATE
	MessageType.GC_SPRITE_EQUIP_STATE = 6370
	-- CG_SPRITE_LEVELUP
	MessageType.CG_SPRITE_LEVELUP = 6371
	-- GC_UPDATE_SPRITE
	MessageType.GC_UPDATE_SPRITE = 6372
	-- CG_DROP_SPRITE
	MessageType.CG_DROP_SPRITE = 6373
	-- GC_DROP_SPRITE
	MessageType.GC_DROP_SPRITE = 6374
	-- GC_ACTIVATE_BUFF
	MessageType.GC_ACTIVATE_BUFF = 6375
	-- CG_OPEN_STAR_MAP_PANEL
	MessageType.CG_OPEN_STAR_MAP_PANEL = 6376
	-- GC_OPEN_STAR_MAP_PANEL
	MessageType.GC_OPEN_STAR_MAP_PANEL = 6377
	-- CG_GET_SIGN_LIST
	MessageType.CG_GET_SIGN_LIST = 6378
	-- GC_GET_SIGN_LIST
	MessageType.GC_GET_SIGN_LIST = 6379
	-- CG_ACTIVATE_SIGN
	MessageType.CG_ACTIVATE_SIGN = 6380
	-- GC_ACTIVATE_SIGN
	MessageType.GC_ACTIVATE_SIGN = 6381
	-- GC_ACTIVATE_NEW_STAR_MAP
	MessageType.GC_ACTIVATE_NEW_STAR_MAP = 6382
	-- CG_OPEN_FIRST_RECHARGE_PANEL
	MessageType.CG_OPEN_FIRST_RECHARGE_PANEL = 6451
	-- GC_OPEN_FIRST_RECHARGE_PANEL
	MessageType.GC_OPEN_FIRST_RECHARGE_PANEL = 6452
	-- CG_GET_FIRST_RECHARGE_REWARD
	MessageType.CG_GET_FIRST_RECHARGE_REWARD = 6453
	-- GC_GET_FIRST_RECHARGE_REWARD
	MessageType.GC_GET_FIRST_RECHARGE_REWARD = 6454
	-- CG_OPEN_RECHARGE_ACTIVITY_PANEL
	MessageType.CG_OPEN_RECHARGE_ACTIVITY_PANEL = 6455
	-- GC_OPEN_RECHARGE_ACTIVITY_PANEL
	MessageType.GC_OPEN_RECHARGE_ACTIVITY_PANEL = 6456
	-- CG_SHOW_SINGLE_RECHARGE_TAB
	MessageType.CG_SHOW_SINGLE_RECHARGE_TAB = 6501
	-- GC_SHOW_SINGLE_RECHARGE_TAB
	MessageType.GC_SHOW_SINGLE_RECHARGE_TAB = 6502
	-- CG_GET_SINGLE_RECHARGE_REWARD
	MessageType.CG_GET_SINGLE_RECHARGE_REWARD = 6503
	-- GC_GET_SINGLE_RECHARGE_REWARD
	MessageType.GC_GET_SINGLE_RECHARGE_REWARD = 6504
	-- CG_SHOW_TOTAL_RECHARGE_TAB
	MessageType.CG_SHOW_TOTAL_RECHARGE_TAB = 6551
	-- GC_SHOW_TOTAL_RECHARGE_TAB
	MessageType.GC_SHOW_TOTAL_RECHARGE_TAB = 6552
	-- CG_GET_TOTAL_RECHARGE_REWARD
	MessageType.CG_GET_TOTAL_RECHARGE_REWARD = 6553
	-- GC_GET_TOTAL_RECHARGE_REWARD
	MessageType.GC_GET_TOTAL_RECHARGE_REWARD = 6554
	-- CG_OPEN_ATTACH_MAGIC_PANEL
	MessageType.CG_OPEN_ATTACH_MAGIC_PANEL = 6601
	-- GC_OPEN_ATTACH_MAGIC_PANEL
	MessageType.GC_OPEN_ATTACH_MAGIC_PANEL = 6602
	-- CG_GET_MAGIC_INFO
	MessageType.CG_GET_MAGIC_INFO = 6603
	-- GC_GET_MAGIC_INFO
	MessageType.GC_GET_MAGIC_INFO = 6604
	-- CG_CHANGE_SKILL_DEVELOP_TYPE
	MessageType.CG_CHANGE_SKILL_DEVELOP_TYPE = 6605
	-- GC_CHANGE_SKILL_DEVELOP_TYPE
	MessageType.GC_CHANGE_SKILL_DEVELOP_TYPE = 6606
	-- CG_OPEN_FACTION_PANEL
	MessageType.CG_OPEN_FACTION_PANEL = 6607
	-- GC_OPEN_FACTION_PANEL
	MessageType.GC_OPEN_FACTION_PANEL = 6608
	-- GC_OPEN_SELECT_FACTION_PANEL
	MessageType.GC_OPEN_SELECT_FACTION_PANEL = 6609
	-- CG_SELECT_FACTION
	MessageType.CG_SELECT_FACTION = 6610
	-- GC_SELECT_FACTION
	MessageType.GC_SELECT_FACTION = 6611
	-- CG_RANDOM_SELECT_FACTION
	MessageType.CG_RANDOM_SELECT_FACTION = 6612
	-- CG_OPEN_MARS_PANEL
	MessageType.CG_OPEN_MARS_PANEL = 6701
	-- GC_OPEN_MARS_PANEL
	MessageType.GC_OPEN_MARS_PANEL = 6702
	-- CG_RFRESH_MARS_ROOM
	MessageType.CG_RFRESH_MARS_ROOM = 6703
	-- GC_RFRESH_MARS_ROOM
	MessageType.GC_RFRESH_MARS_ROOM = 6704
	-- CG_KILL_MARS_PLAYER
	MessageType.CG_KILL_MARS_PLAYER = 6705
	-- GC_KILL_MARS_PLAYER
	MessageType.GC_KILL_MARS_PLAYER = 6706
	-- CG_UNLOCK_MARS_ROOM
	MessageType.CG_UNLOCK_MARS_ROOM = 6707
	-- GC_UNLOCK_MARS_ROOM
	MessageType.GC_UNLOCK_MARS_ROOM = 6708
	-- CG_BUY_MARS_MULTIPLE_NUM
	MessageType.CG_BUY_MARS_MULTIPLE_NUM = 6709
	-- GC_BUY_MARS_MULTIPLE_NUM
	MessageType.GC_BUY_MARS_MULTIPLE_NUM = 6710
	-- CG_OPEN_MARS_RANK_PANEL
	MessageType.CG_OPEN_MARS_RANK_PANEL = 6711
	-- GC_OPEN_MARS_RANK_PANEL
	MessageType.GC_OPEN_MARS_RANK_PANEL = 6712
	-- CG_GET_MARS_KILL_REWARD
	MessageType.CG_GET_MARS_KILL_REWARD = 4363
	-- GC_GET_MARS_KILL_REWARD
	MessageType.GC_GET_MARS_KILL_REWARD = 4364
	-- CG_OPEN_TARGET_PANEL
	MessageType.CG_OPEN_TARGET_PANEL = 6751
	-- GC_OPEN_TARGET_PANEL
	MessageType.GC_OPEN_TARGET_PANEL = 6752
	-- CG_GET_TARGET_REWARD
	MessageType.CG_GET_TARGET_REWARD = 6753
	-- GC_GET_TARGET_REWARD
	MessageType.GC_GET_TARGET_REWARD = 6754
	-- GC_UPDATE_TARGET_PANEL
	MessageType.GC_UPDATE_TARGET_PANEL = 6755
	-- GC_JOIN_LEGION_BOSS_WAR
	MessageType.GC_JOIN_LEGION_BOSS_WAR = 6801
	-- CG_ENCOURAGE_LEGION_BOSS_WAR
	MessageType.CG_ENCOURAGE_LEGION_BOSS_WAR = 6802
	-- GC_ENCOURAGE_LEGION_BOSS_WAR
	MessageType.GC_ENCOURAGE_LEGION_BOSS_WAR = 6803
	-- CG_CHARGED_LEGION_BOSS_WAR
	MessageType.CG_CHARGED_LEGION_BOSS_WAR = 6804
	-- GC_CHARGED_LEGION_BOSS_WAR
	MessageType.GC_CHARGED_LEGION_BOSS_WAR = 6805
	-- CG_CHARGED_LEGION_BOSS
	MessageType.CG_CHARGED_LEGION_BOSS = 6806
	-- CG_ATTACK_LEGION_BOSS
	MessageType.CG_ATTACK_LEGION_BOSS = 6807
	-- GC_HAS_LEGION_BOSS_REWARD
	MessageType.GC_HAS_LEGION_BOSS_REWARD = 6808
	-- CG_ENTER_LEGION_BOSS_WAR
	MessageType.CG_ENTER_LEGION_BOSS_WAR = 6809
	-- GC_CHARGED_LEGION_BOSS
	MessageType.GC_CHARGED_LEGION_BOSS = 6810
	-- CG_OPEN_LEGION_MINE_WAR_PANEL
	MessageType.CG_OPEN_LEGION_MINE_WAR_PANEL = 6851
	-- GC_OPEN_LEGION_MINE_WAR_PANEL
	MessageType.GC_OPEN_LEGION_MINE_WAR_PANEL = 6852
	-- CG_LEGION_MINE_WAR_MOVE
	MessageType.CG_LEGION_MINE_WAR_MOVE = 6853
	-- CG_LEGION_MINE_WAR_WATCH
	MessageType.CG_LEGION_MINE_WAR_WATCH = 6854
	-- GC_UPDATE_LEGION_MINE_LIST
	MessageType.GC_UPDATE_LEGION_MINE_LIST = 6855
	-- GC_UPDATE_LEGION_BUF_LIST
	MessageType.GC_UPDATE_LEGION_BUF_LIST = 6856
	-- CG_USE_SELF_BUF
	MessageType.CG_USE_SELF_BUF = 6857
	-- GC_USE_SELF_BUF
	MessageType.GC_USE_SELF_BUF = 6858
	-- CG_ABORT_SELF_BUF
	MessageType.CG_ABORT_SELF_BUF = 6859
	-- GC_ABORT_SELF_BUF
	MessageType.GC_ABORT_SELF_BUF = 6860
	-- CG_LEGION_MINE_WAR_HARVEST
	MessageType.CG_LEGION_MINE_WAR_HARVEST = 6861
	-- GC_LEGION_MINE_WAR_HARVEST
	MessageType.GC_LEGION_MINE_WAR_HARVEST = 6862
	-- CG_LEGION_MINE_WAR_BATTLE
	MessageType.CG_LEGION_MINE_WAR_BATTLE = 6863
	-- CG_LEGION_MINE_WAR_ENCOURAGE
	MessageType.CG_LEGION_MINE_WAR_ENCOURAGE = 6864
	-- GC_LEGION_MINE_WAR_ENCOURAGE
	MessageType.GC_LEGION_MINE_WAR_ENCOURAGE = 6865
	-- CG_LEGION_MINE_WAR_QUIT
	MessageType.CG_LEGION_MINE_WAR_QUIT = 6866
	-- GC_LEGION_MINE_WAR_END
	MessageType.GC_LEGION_MINE_WAR_END = 6867
	-- GC_UPDATE_MINE_WAR_INFO
	MessageType.GC_UPDATE_MINE_WAR_INFO = 6868
	-- CG_OPEN_NOSTRUM_PANEL
	MessageType.CG_OPEN_NOSTRUM_PANEL = 6901
	-- GC_OPEN_NOSTRUM_PANEL
	MessageType.GC_OPEN_NOSTRUM_PANEL = 6902
	-- CG_OPEN_ESCORT_PANEL
	MessageType.CG_OPEN_ESCORT_PANEL = 6951
	-- CG_CLOSE_ESCORT_PANEL
	MessageType.CG_CLOSE_ESCORT_PANEL = 6952
	-- GC_UPDATE_ESCORT_PANEL
	MessageType.GC_UPDATE_ESCORT_PANEL = 6953
	-- CG_SHOW_MONSTER_TAB
	MessageType.CG_SHOW_MONSTER_TAB = 6954
	-- GC_SHOW_MONSTER_TAB
	MessageType.GC_SHOW_MONSTER_TAB = 6955
	-- CG_SHOW_ESCORT_TAB
	MessageType.CG_SHOW_ESCORT_TAB = 6956
	-- GC_SHOW_ESCORT_TAB
	MessageType.GC_SHOW_ESCORT_TAB = 6957
	-- CG_ROB_ESCROT
	MessageType.CG_ROB_ESCROT = 6958
	-- CG_ESCORT_REFRESH_MONSTER
	MessageType.CG_ESCORT_REFRESH_MONSTER = 6959
	-- GC_ESCORT_REFRESH_MONSTER
	MessageType.GC_ESCORT_REFRESH_MONSTER = 6960
	-- CG_ESCORT_CALL_MONSTER
	MessageType.CG_ESCORT_CALL_MONSTER = 6961
	-- GC_ESCORT_CALL_MONSTER
	MessageType.GC_ESCORT_CALL_MONSTER = 6962
	-- CG_ESCORT_INVITE_FRIEND
	MessageType.CG_ESCORT_INVITE_FRIEND = 6963
	-- GC_ESCORT_INVITE_FRIEND
	MessageType.GC_ESCORT_INVITE_FRIEND = 6964
	-- GC_ESCORT_INVITE_FRIEND_APPLY
	MessageType.GC_ESCORT_INVITE_FRIEND_APPLY = 6965
	-- CG_ESCORT_ABORT_INVITE
	MessageType.CG_ESCORT_ABORT_INVITE = 6966
	-- GC_ESCORT_ABORT_INVITE
	MessageType.GC_ESCORT_ABORT_INVITE = 6967
	-- CG_ESCORT_AGREE_INVITE
	MessageType.CG_ESCORT_AGREE_INVITE = 6968
	-- GC_ESCORT_AGREE_INVITE
	MessageType.GC_ESCORT_AGREE_INVITE = 6969
	-- CG_ESCORT_REJECT_INVITE
	MessageType.CG_ESCORT_REJECT_INVITE = 6970
	-- GC_ESCORT_REJECT_INVITE
	MessageType.GC_ESCORT_REJECT_INVITE = 6971
	-- CG_START_ESCORT
	MessageType.CG_START_ESCORT = 6972
	-- GC_START_ESCORT
	MessageType.GC_START_ESCORT = 6973
	-- CG_ESCORT_LEGION_PRAY
	MessageType.CG_ESCORT_LEGION_PRAY = 6974
	-- GC_ESCORT_LEGION_PRAY
	MessageType.GC_ESCORT_LEGION_PRAY = 6975
	-- CG_SHOW_ROB_RANK_TAB
	MessageType.CG_SHOW_ROB_RANK_TAB = 6976
	-- GC_SHOW_ROB_RANK_TAB
	MessageType.GC_SHOW_ROB_RANK_TAB = 6977
	-- CG_ESCORT_GET_REWARD
	MessageType.CG_ESCORT_GET_REWARD = 6978
	-- GC_ESCORT_GET_REWARD
	MessageType.GC_ESCORT_GET_REWARD = 6979
	-- CG_ESCORT_BUY_ROB_NUM
	MessageType.CG_ESCORT_BUY_ROB_NUM = 6980
	-- GC_ESCORT_BUY_ROB_NUM
	MessageType.GC_ESCORT_BUY_ROB_NUM = 6981
	-- CG_OPEN_PREDICT_PANEL
	MessageType.CG_OPEN_PREDICT_PANEL = 7001
	-- GC_OPEN_PREDICT_PANEL
	MessageType.GC_OPEN_PREDICT_PANEL = 7002
	-- CG_SHOW_PREDICT_LIST
	MessageType.CG_SHOW_PREDICT_LIST = 7003
	-- GC_SHOW_PREDICT_LIST
	MessageType.GC_SHOW_PREDICT_LIST = 7004
	-- CG_ACTIVATE_PREDICT
	MessageType.CG_ACTIVATE_PREDICT = 7005
	-- GC_ACTIVATE_PREDICT
	MessageType.GC_ACTIVATE_PREDICT = 7006

return MessageType