// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Friend.proto

package com.hifun.soul.proto.common;

public final class Friends {
  private Friends() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FriendOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 passportId = 1;
    boolean hasPassportId();
    long getPassportId();
    
    // required string passportName = 2;
    boolean hasPassportName();
    String getPassportName();
    
    // required int64 roleId = 3;
    boolean hasRoleId();
    long getRoleId();
    
    // required string roleName = 4;
    boolean hasRoleName();
    String getRoleName();
    
    // required int32 icon = 5;
    boolean hasIcon();
    int getIcon();
    
    // required int32 level = 6;
    boolean hasLevel();
    int getLevel();
    
    // optional int32 occupation = 7;
    boolean hasOccupation();
    int getOccupation();
  }
  public static final class Friend extends
      com.google.protobuf.GeneratedMessage
      implements FriendOrBuilder {
    // Use Friend.newBuilder() to construct.
    private Friend(Builder builder) {
      super(builder);
    }
    private Friend(boolean noInit) {}
    
    private static final Friend defaultInstance;
    public static Friend getDefaultInstance() {
      return defaultInstance;
    }
    
    public Friend getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Friends.internal_static_com_hifun_soul_proto_common_Friend_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Friends.internal_static_com_hifun_soul_proto_common_Friend_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 passportId = 1;
    public static final int PASSPORTID_FIELD_NUMBER = 1;
    private long passportId_;
    public boolean hasPassportId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getPassportId() {
      return passportId_;
    }
    
    // required string passportName = 2;
    public static final int PASSPORTNAME_FIELD_NUMBER = 2;
    private java.lang.Object passportName_;
    public boolean hasPassportName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassportName() {
      java.lang.Object ref = passportName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          passportName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPassportNameBytes() {
      java.lang.Object ref = passportName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        passportName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 roleId = 3;
    public static final int ROLEID_FIELD_NUMBER = 3;
    private long roleId_;
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getRoleId() {
      return roleId_;
    }
    
    // required string roleName = 4;
    public static final int ROLENAME_FIELD_NUMBER = 4;
    private java.lang.Object roleName_;
    public boolean hasRoleName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getRoleName() {
      java.lang.Object ref = roleName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          roleName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoleNameBytes() {
      java.lang.Object ref = roleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        roleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 icon = 5;
    public static final int ICON_FIELD_NUMBER = 5;
    private int icon_;
    public boolean hasIcon() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getIcon() {
      return icon_;
    }
    
    // required int32 level = 6;
    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getLevel() {
      return level_;
    }
    
    // optional int32 occupation = 7;
    public static final int OCCUPATION_FIELD_NUMBER = 7;
    private int occupation_;
    public boolean hasOccupation() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getOccupation() {
      return occupation_;
    }
    
    private void initFields() {
      passportId_ = 0L;
      passportName_ = "";
      roleId_ = 0L;
      roleName_ = "";
      icon_ = 0;
      level_ = 0;
      occupation_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPassportId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassportName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, passportId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPassportNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, roleId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRoleNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, icon_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, occupation_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, passportId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPassportNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, roleId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRoleNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, icon_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, occupation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Friends.Friend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Friends.Friend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Friends.FriendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Friends.internal_static_com_hifun_soul_proto_common_Friend_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Friends.internal_static_com_hifun_soul_proto_common_Friend_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Friends.Friend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        passportId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        passportName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        roleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        roleName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        icon_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        occupation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Friends.Friend.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Friends.Friend getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Friends.Friend.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Friends.Friend build() {
        com.hifun.soul.proto.common.Friends.Friend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Friends.Friend buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Friends.Friend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Friends.Friend buildPartial() {
        com.hifun.soul.proto.common.Friends.Friend result = new com.hifun.soul.proto.common.Friends.Friend(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.passportId_ = passportId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passportName_ = passportName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.roleName_ = roleName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.icon_ = icon_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.occupation_ = occupation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Friends.Friend) {
          return mergeFrom((com.hifun.soul.proto.common.Friends.Friend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Friends.Friend other) {
        if (other == com.hifun.soul.proto.common.Friends.Friend.getDefaultInstance()) return this;
        if (other.hasPassportId()) {
          setPassportId(other.getPassportId());
        }
        if (other.hasPassportName()) {
          setPassportName(other.getPassportName());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasRoleName()) {
          setRoleName(other.getRoleName());
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasOccupation()) {
          setOccupation(other.getOccupation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPassportId()) {
          
          return false;
        }
        if (!hasPassportName()) {
          
          return false;
        }
        if (!hasRoleId()) {
          
          return false;
        }
        if (!hasRoleName()) {
          
          return false;
        }
        if (!hasIcon()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              passportId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              passportName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              roleId_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              roleName_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              icon_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              level_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              occupation_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 passportId = 1;
      private long passportId_ ;
      public boolean hasPassportId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getPassportId() {
        return passportId_;
      }
      public Builder setPassportId(long value) {
        bitField0_ |= 0x00000001;
        passportId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassportId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        passportId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string passportName = 2;
      private java.lang.Object passportName_ = "";
      public boolean hasPassportName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassportName() {
        java.lang.Object ref = passportName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          passportName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassportName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passportName_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassportName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passportName_ = getDefaultInstance().getPassportName();
        onChanged();
        return this;
      }
      void setPassportName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        passportName_ = value;
        onChanged();
      }
      
      // required int64 roleId = 3;
      private long roleId_ ;
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getRoleId() {
        return roleId_;
      }
      public Builder setRoleId(long value) {
        bitField0_ |= 0x00000004;
        roleId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roleId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string roleName = 4;
      private java.lang.Object roleName_ = "";
      public boolean hasRoleName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getRoleName() {
        java.lang.Object ref = roleName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          roleName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRoleName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        roleName_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        roleName_ = getDefaultInstance().getRoleName();
        onChanged();
        return this;
      }
      void setRoleName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        roleName_ = value;
        onChanged();
      }
      
      // required int32 icon = 5;
      private int icon_ ;
      public boolean hasIcon() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getIcon() {
        return icon_;
      }
      public Builder setIcon(int value) {
        bitField0_ |= 0x00000010;
        icon_ = value;
        onChanged();
        return this;
      }
      public Builder clearIcon() {
        bitField0_ = (bitField0_ & ~0x00000010);
        icon_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 level = 6;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000020;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 occupation = 7;
      private int occupation_ ;
      public boolean hasOccupation() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getOccupation() {
        return occupation_;
      }
      public Builder setOccupation(int value) {
        bitField0_ |= 0x00000040;
        occupation_ = value;
        onChanged();
        return this;
      }
      public Builder clearOccupation() {
        bitField0_ = (bitField0_ & ~0x00000040);
        occupation_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.Friend)
    }
    
    static {
      defaultInstance = new Friend(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.Friend)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_Friend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_Friend_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Friend.proto\022\033com.hifun.soul.proto.com" +
      "mon\"\205\001\n\006Friend\022\022\n\npassportId\030\001 \002(\003\022\024\n\014pa" +
      "ssportName\030\002 \002(\t\022\016\n\006roleId\030\003 \002(\003\022\020\n\010role" +
      "Name\030\004 \002(\t\022\014\n\004icon\030\005 \002(\005\022\r\n\005level\030\006 \002(\005\022" +
      "\022\n\noccupation\030\007 \001(\005B&\n\033com.hifun.soul.pr" +
      "oto.commonB\007Friends"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hifun_soul_proto_common_Friend_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hifun_soul_proto_common_Friend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_Friend_descriptor,
              new java.lang.String[] { "PassportId", "PassportName", "RoleId", "RoleName", "Icon", "Level", "Occupation", },
              com.hifun.soul.proto.common.Friends.Friend.class,
              com.hifun.soul.proto.common.Friends.Friend.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
