// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mars.proto

package com.hifun.soul.proto.common;

public final class Mars {
  private Mars() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MarsRoomOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 roomType = 1;
    boolean hasRoomType();
    int getRoomType();
    
    // required int32 ownerType = 2;
    boolean hasOwnerType();
    int getOwnerType();
    
    // required int32 isLocked = 3;
    boolean hasIsLocked();
    int getIsLocked();
    
    // required int64 ownerId = 4;
    boolean hasOwnerId();
    long getOwnerId();
    
    // required string ownerName = 5;
    boolean hasOwnerName();
    String getOwnerName();
    
    // required int32 ownerOccupation = 6;
    boolean hasOwnerOccupation();
    int getOwnerOccupation();
    
    // required int32 ownerLevel = 7;
    boolean hasOwnerLevel();
    int getOwnerLevel();
    
    // optional int32 todayKillValue = 8;
    boolean hasTodayKillValue();
    int getTodayKillValue();
  }
  public static final class MarsRoom extends
      com.google.protobuf.GeneratedMessage
      implements MarsRoomOrBuilder {
    // Use MarsRoom.newBuilder() to construct.
    private MarsRoom(Builder builder) {
      super(builder);
    }
    private MarsRoom(boolean noInit) {}
    
    private static final MarsRoom defaultInstance;
    public static MarsRoom getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarsRoom getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsRoom_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsRoom_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 roomType = 1;
    public static final int ROOMTYPE_FIELD_NUMBER = 1;
    private int roomType_;
    public boolean hasRoomType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRoomType() {
      return roomType_;
    }
    
    // required int32 ownerType = 2;
    public static final int OWNERTYPE_FIELD_NUMBER = 2;
    private int ownerType_;
    public boolean hasOwnerType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getOwnerType() {
      return ownerType_;
    }
    
    // required int32 isLocked = 3;
    public static final int ISLOCKED_FIELD_NUMBER = 3;
    private int isLocked_;
    public boolean hasIsLocked() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getIsLocked() {
      return isLocked_;
    }
    
    // required int64 ownerId = 4;
    public static final int OWNERID_FIELD_NUMBER = 4;
    private long ownerId_;
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getOwnerId() {
      return ownerId_;
    }
    
    // required string ownerName = 5;
    public static final int OWNERNAME_FIELD_NUMBER = 5;
    private java.lang.Object ownerName_;
    public boolean hasOwnerName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getOwnerName() {
      java.lang.Object ref = ownerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ownerName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOwnerNameBytes() {
      java.lang.Object ref = ownerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ownerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 ownerOccupation = 6;
    public static final int OWNEROCCUPATION_FIELD_NUMBER = 6;
    private int ownerOccupation_;
    public boolean hasOwnerOccupation() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getOwnerOccupation() {
      return ownerOccupation_;
    }
    
    // required int32 ownerLevel = 7;
    public static final int OWNERLEVEL_FIELD_NUMBER = 7;
    private int ownerLevel_;
    public boolean hasOwnerLevel() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getOwnerLevel() {
      return ownerLevel_;
    }
    
    // optional int32 todayKillValue = 8;
    public static final int TODAYKILLVALUE_FIELD_NUMBER = 8;
    private int todayKillValue_;
    public boolean hasTodayKillValue() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getTodayKillValue() {
      return todayKillValue_;
    }
    
    private void initFields() {
      roomType_ = 0;
      ownerType_ = 0;
      isLocked_ = 0;
      ownerId_ = 0L;
      ownerName_ = "";
      ownerOccupation_ = 0;
      ownerLevel_ = 0;
      todayKillValue_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRoomType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwnerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsLocked()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwnerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwnerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwnerOccupation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwnerLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, roomType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ownerType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, isLocked_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, ownerId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getOwnerNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, ownerOccupation_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, ownerLevel_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, todayKillValue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ownerType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, isLocked_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, ownerId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getOwnerNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ownerOccupation_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, ownerLevel_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, todayKillValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Mars.MarsRoom prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Mars.MarsRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsRoom_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsRoom_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Mars.MarsRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        roomType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ownerType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isLocked_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        ownerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        ownerOccupation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        ownerLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        todayKillValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Mars.MarsRoom.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Mars.MarsRoom getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Mars.MarsRoom.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Mars.MarsRoom build() {
        com.hifun.soul.proto.common.Mars.MarsRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Mars.MarsRoom buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Mars.MarsRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Mars.MarsRoom buildPartial() {
        com.hifun.soul.proto.common.Mars.MarsRoom result = new com.hifun.soul.proto.common.Mars.MarsRoom(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomType_ = roomType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ownerType_ = ownerType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isLocked_ = isLocked_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ownerId_ = ownerId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ownerName_ = ownerName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ownerOccupation_ = ownerOccupation_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ownerLevel_ = ownerLevel_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.todayKillValue_ = todayKillValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Mars.MarsRoom) {
          return mergeFrom((com.hifun.soul.proto.common.Mars.MarsRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Mars.MarsRoom other) {
        if (other == com.hifun.soul.proto.common.Mars.MarsRoom.getDefaultInstance()) return this;
        if (other.hasRoomType()) {
          setRoomType(other.getRoomType());
        }
        if (other.hasOwnerType()) {
          setOwnerType(other.getOwnerType());
        }
        if (other.hasIsLocked()) {
          setIsLocked(other.getIsLocked());
        }
        if (other.hasOwnerId()) {
          setOwnerId(other.getOwnerId());
        }
        if (other.hasOwnerName()) {
          setOwnerName(other.getOwnerName());
        }
        if (other.hasOwnerOccupation()) {
          setOwnerOccupation(other.getOwnerOccupation());
        }
        if (other.hasOwnerLevel()) {
          setOwnerLevel(other.getOwnerLevel());
        }
        if (other.hasTodayKillValue()) {
          setTodayKillValue(other.getTodayKillValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRoomType()) {
          
          return false;
        }
        if (!hasOwnerType()) {
          
          return false;
        }
        if (!hasIsLocked()) {
          
          return false;
        }
        if (!hasOwnerId()) {
          
          return false;
        }
        if (!hasOwnerName()) {
          
          return false;
        }
        if (!hasOwnerOccupation()) {
          
          return false;
        }
        if (!hasOwnerLevel()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roomType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ownerType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isLocked_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ownerId_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              ownerName_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ownerOccupation_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              ownerLevel_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              todayKillValue_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 roomType = 1;
      private int roomType_ ;
      public boolean hasRoomType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRoomType() {
        return roomType_;
      }
      public Builder setRoomType(int value) {
        bitField0_ |= 0x00000001;
        roomType_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoomType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomType_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 ownerType = 2;
      private int ownerType_ ;
      public boolean hasOwnerType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getOwnerType() {
        return ownerType_;
      }
      public Builder setOwnerType(int value) {
        bitField0_ |= 0x00000002;
        ownerType_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ownerType_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 isLocked = 3;
      private int isLocked_ ;
      public boolean hasIsLocked() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getIsLocked() {
        return isLocked_;
      }
      public Builder setIsLocked(int value) {
        bitField0_ |= 0x00000004;
        isLocked_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsLocked() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isLocked_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 ownerId = 4;
      private long ownerId_ ;
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getOwnerId() {
        return ownerId_;
      }
      public Builder setOwnerId(long value) {
        bitField0_ |= 0x00000008;
        ownerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ownerId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string ownerName = 5;
      private java.lang.Object ownerName_ = "";
      public boolean hasOwnerName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getOwnerName() {
        java.lang.Object ref = ownerName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ownerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOwnerName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ownerName_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ownerName_ = getDefaultInstance().getOwnerName();
        onChanged();
        return this;
      }
      void setOwnerName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        ownerName_ = value;
        onChanged();
      }
      
      // required int32 ownerOccupation = 6;
      private int ownerOccupation_ ;
      public boolean hasOwnerOccupation() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getOwnerOccupation() {
        return ownerOccupation_;
      }
      public Builder setOwnerOccupation(int value) {
        bitField0_ |= 0x00000020;
        ownerOccupation_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerOccupation() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ownerOccupation_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 ownerLevel = 7;
      private int ownerLevel_ ;
      public boolean hasOwnerLevel() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getOwnerLevel() {
        return ownerLevel_;
      }
      public Builder setOwnerLevel(int value) {
        bitField0_ |= 0x00000040;
        ownerLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearOwnerLevel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ownerLevel_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 todayKillValue = 8;
      private int todayKillValue_ ;
      public boolean hasTodayKillValue() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getTodayKillValue() {
        return todayKillValue_;
      }
      public Builder setTodayKillValue(int value) {
        bitField0_ |= 0x00000080;
        todayKillValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearTodayKillValue() {
        bitField0_ = (bitField0_ & ~0x00000080);
        todayKillValue_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.MarsRoom)
    }
    
    static {
      defaultInstance = new MarsRoom(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.MarsRoom)
  }
  
  public interface MarsLoserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 loserId = 1;
    boolean hasLoserId();
    long getLoserId();
    
    // required string loserName = 2;
    boolean hasLoserName();
    String getLoserName();
    
    // required int32 loserOccupation = 3;
    boolean hasLoserOccupation();
    int getLoserOccupation();
    
    // required int32 loserLevel = 4;
    boolean hasLoserLevel();
    int getLoserLevel();
    
    // optional int32 todayKillValue = 5;
    boolean hasTodayKillValue();
    int getTodayKillValue();
    
    // optional int32 isLoser = 6;
    boolean hasIsLoser();
    int getIsLoser();
    
    // required int32 playerType = 7;
    boolean hasPlayerType();
    int getPlayerType();
    
    // optional int64 killTime = 8;
    boolean hasKillTime();
    long getKillTime();
  }
  public static final class MarsLoser extends
      com.google.protobuf.GeneratedMessage
      implements MarsLoserOrBuilder {
    // Use MarsLoser.newBuilder() to construct.
    private MarsLoser(Builder builder) {
      super(builder);
    }
    private MarsLoser(boolean noInit) {}
    
    private static final MarsLoser defaultInstance;
    public static MarsLoser getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarsLoser getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsLoser_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsLoser_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 loserId = 1;
    public static final int LOSERID_FIELD_NUMBER = 1;
    private long loserId_;
    public boolean hasLoserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLoserId() {
      return loserId_;
    }
    
    // required string loserName = 2;
    public static final int LOSERNAME_FIELD_NUMBER = 2;
    private java.lang.Object loserName_;
    public boolean hasLoserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLoserName() {
      java.lang.Object ref = loserName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          loserName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLoserNameBytes() {
      java.lang.Object ref = loserName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        loserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 loserOccupation = 3;
    public static final int LOSEROCCUPATION_FIELD_NUMBER = 3;
    private int loserOccupation_;
    public boolean hasLoserOccupation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLoserOccupation() {
      return loserOccupation_;
    }
    
    // required int32 loserLevel = 4;
    public static final int LOSERLEVEL_FIELD_NUMBER = 4;
    private int loserLevel_;
    public boolean hasLoserLevel() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getLoserLevel() {
      return loserLevel_;
    }
    
    // optional int32 todayKillValue = 5;
    public static final int TODAYKILLVALUE_FIELD_NUMBER = 5;
    private int todayKillValue_;
    public boolean hasTodayKillValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getTodayKillValue() {
      return todayKillValue_;
    }
    
    // optional int32 isLoser = 6;
    public static final int ISLOSER_FIELD_NUMBER = 6;
    private int isLoser_;
    public boolean hasIsLoser() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getIsLoser() {
      return isLoser_;
    }
    
    // required int32 playerType = 7;
    public static final int PLAYERTYPE_FIELD_NUMBER = 7;
    private int playerType_;
    public boolean hasPlayerType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getPlayerType() {
      return playerType_;
    }
    
    // optional int64 killTime = 8;
    public static final int KILLTIME_FIELD_NUMBER = 8;
    private long killTime_;
    public boolean hasKillTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getKillTime() {
      return killTime_;
    }
    
    private void initFields() {
      loserId_ = 0L;
      loserName_ = "";
      loserOccupation_ = 0;
      loserLevel_ = 0;
      todayKillValue_ = 0;
      isLoser_ = 0;
      playerType_ = 0;
      killTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLoserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoserOccupation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoserLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, loserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLoserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, loserOccupation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, loserLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, todayKillValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, isLoser_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, playerType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, killTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, loserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLoserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, loserOccupation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, loserLevel_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, todayKillValue_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, isLoser_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, playerType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, killTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mars.MarsLoser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Mars.MarsLoser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Mars.MarsLoserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsLoser_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Mars.internal_static_com_hifun_soul_proto_common_MarsLoser_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Mars.MarsLoser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        loserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        loserName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        loserOccupation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        loserLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        todayKillValue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        isLoser_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        playerType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        killTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Mars.MarsLoser.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Mars.MarsLoser getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Mars.MarsLoser.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Mars.MarsLoser build() {
        com.hifun.soul.proto.common.Mars.MarsLoser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Mars.MarsLoser buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Mars.MarsLoser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Mars.MarsLoser buildPartial() {
        com.hifun.soul.proto.common.Mars.MarsLoser result = new com.hifun.soul.proto.common.Mars.MarsLoser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loserId_ = loserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loserName_ = loserName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.loserOccupation_ = loserOccupation_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.loserLevel_ = loserLevel_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.todayKillValue_ = todayKillValue_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isLoser_ = isLoser_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.playerType_ = playerType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.killTime_ = killTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Mars.MarsLoser) {
          return mergeFrom((com.hifun.soul.proto.common.Mars.MarsLoser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Mars.MarsLoser other) {
        if (other == com.hifun.soul.proto.common.Mars.MarsLoser.getDefaultInstance()) return this;
        if (other.hasLoserId()) {
          setLoserId(other.getLoserId());
        }
        if (other.hasLoserName()) {
          setLoserName(other.getLoserName());
        }
        if (other.hasLoserOccupation()) {
          setLoserOccupation(other.getLoserOccupation());
        }
        if (other.hasLoserLevel()) {
          setLoserLevel(other.getLoserLevel());
        }
        if (other.hasTodayKillValue()) {
          setTodayKillValue(other.getTodayKillValue());
        }
        if (other.hasIsLoser()) {
          setIsLoser(other.getIsLoser());
        }
        if (other.hasPlayerType()) {
          setPlayerType(other.getPlayerType());
        }
        if (other.hasKillTime()) {
          setKillTime(other.getKillTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLoserId()) {
          
          return false;
        }
        if (!hasLoserName()) {
          
          return false;
        }
        if (!hasLoserOccupation()) {
          
          return false;
        }
        if (!hasLoserLevel()) {
          
          return false;
        }
        if (!hasPlayerType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              loserId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              loserName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              loserOccupation_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              loserLevel_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              todayKillValue_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              isLoser_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              playerType_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              killTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 loserId = 1;
      private long loserId_ ;
      public boolean hasLoserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLoserId() {
        return loserId_;
      }
      public Builder setLoserId(long value) {
        bitField0_ |= 0x00000001;
        loserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loserId_ = 0L;
        onChanged();
        return this;
      }
      
      // required string loserName = 2;
      private java.lang.Object loserName_ = "";
      public boolean hasLoserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLoserName() {
        java.lang.Object ref = loserName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          loserName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLoserName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        loserName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loserName_ = getDefaultInstance().getLoserName();
        onChanged();
        return this;
      }
      void setLoserName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        loserName_ = value;
        onChanged();
      }
      
      // required int32 loserOccupation = 3;
      private int loserOccupation_ ;
      public boolean hasLoserOccupation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLoserOccupation() {
        return loserOccupation_;
      }
      public Builder setLoserOccupation(int value) {
        bitField0_ |= 0x00000004;
        loserOccupation_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoserOccupation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        loserOccupation_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 loserLevel = 4;
      private int loserLevel_ ;
      public boolean hasLoserLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getLoserLevel() {
        return loserLevel_;
      }
      public Builder setLoserLevel(int value) {
        bitField0_ |= 0x00000008;
        loserLevel_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoserLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        loserLevel_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 todayKillValue = 5;
      private int todayKillValue_ ;
      public boolean hasTodayKillValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getTodayKillValue() {
        return todayKillValue_;
      }
      public Builder setTodayKillValue(int value) {
        bitField0_ |= 0x00000010;
        todayKillValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearTodayKillValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        todayKillValue_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 isLoser = 6;
      private int isLoser_ ;
      public boolean hasIsLoser() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getIsLoser() {
        return isLoser_;
      }
      public Builder setIsLoser(int value) {
        bitField0_ |= 0x00000020;
        isLoser_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsLoser() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isLoser_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 playerType = 7;
      private int playerType_ ;
      public boolean hasPlayerType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getPlayerType() {
        return playerType_;
      }
      public Builder setPlayerType(int value) {
        bitField0_ |= 0x00000040;
        playerType_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        playerType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 killTime = 8;
      private long killTime_ ;
      public boolean hasKillTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getKillTime() {
        return killTime_;
      }
      public Builder setKillTime(long value) {
        bitField0_ |= 0x00000080;
        killTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearKillTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        killTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.MarsLoser)
    }
    
    static {
      defaultInstance = new MarsLoser(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.MarsLoser)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_MarsRoom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_MarsRoom_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_MarsLoser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_MarsLoser_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nMars.proto\022\033com.hifun.soul.proto.commo" +
      "n\"\252\001\n\010MarsRoom\022\020\n\010roomType\030\001 \002(\005\022\021\n\towne" +
      "rType\030\002 \002(\005\022\020\n\010isLocked\030\003 \002(\005\022\017\n\007ownerId" +
      "\030\004 \002(\003\022\021\n\townerName\030\005 \002(\t\022\027\n\017ownerOccupa" +
      "tion\030\006 \002(\005\022\022\n\nownerLevel\030\007 \002(\005\022\026\n\016todayK" +
      "illValue\030\010 \001(\005\"\253\001\n\tMarsLoser\022\017\n\007loserId\030" +
      "\001 \002(\003\022\021\n\tloserName\030\002 \002(\t\022\027\n\017loserOccupat" +
      "ion\030\003 \002(\005\022\022\n\nloserLevel\030\004 \002(\005\022\026\n\016todayKi" +
      "llValue\030\005 \001(\005\022\017\n\007isLoser\030\006 \001(\005\022\022\n\nplayer" +
      "Type\030\007 \002(\005\022\020\n\010killTime\030\010 \001(\003B#\n\033com.hifu",
      "n.soul.proto.commonB\004Mars"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hifun_soul_proto_common_MarsRoom_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hifun_soul_proto_common_MarsRoom_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_MarsRoom_descriptor,
              new java.lang.String[] { "RoomType", "OwnerType", "IsLocked", "OwnerId", "OwnerName", "OwnerOccupation", "OwnerLevel", "TodayKillValue", },
              com.hifun.soul.proto.common.Mars.MarsRoom.class,
              com.hifun.soul.proto.common.Mars.MarsRoom.Builder.class);
          internal_static_com_hifun_soul_proto_common_MarsLoser_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_hifun_soul_proto_common_MarsLoser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_MarsLoser_descriptor,
              new java.lang.String[] { "LoserId", "LoserName", "LoserOccupation", "LoserLevel", "TodayKillValue", "IsLoser", "PlayerType", "KillTime", },
              com.hifun.soul.proto.common.Mars.MarsLoser.class,
              com.hifun.soul.proto.common.Mars.MarsLoser.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
