// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mine.proto

package com.hifun.soul.proto.common;

public final class Mine {
  private Mine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HumanMineInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 humanGuid = 1;
    boolean hasHumanGuid();
    long getHumanGuid();
    
    // repeated .com.hifun.soul.proto.common.MineField mineFields = 2;
    java.util.List<com.hifun.soul.proto.common.Mine.MineField> 
        getMineFieldsList();
    com.hifun.soul.proto.common.Mine.MineField getMineFields(int index);
    int getMineFieldsCount();
    java.util.List<? extends com.hifun.soul.proto.common.Mine.MineFieldOrBuilder> 
        getMineFieldsOrBuilderList();
    com.hifun.soul.proto.common.Mine.MineFieldOrBuilder getMineFieldsOrBuilder(
        int index);
    
    // optional int32 remainFreeMineNum = 3;
    boolean hasRemainFreeMineNum();
    int getRemainFreeMineNum();
    
    // optional int32 buyMineFieldNum = 4;
    boolean hasBuyMineFieldNum();
    int getBuyMineFieldNum();
    
    // optional int32 resetMineFieldNum = 5;
    boolean hasResetMineFieldNum();
    int getResetMineFieldNum();
    
    // optional int32 remainBoughtMineNum = 6;
    boolean hasRemainBoughtMineNum();
    int getRemainBoughtMineNum();
  }
  public static final class HumanMineInfo extends
      com.google.protobuf.GeneratedMessage
      implements HumanMineInfoOrBuilder {
    // Use HumanMineInfo.newBuilder() to construct.
    private HumanMineInfo(Builder builder) {
      super(builder);
    }
    private HumanMineInfo(boolean noInit) {}
    
    private static final HumanMineInfo defaultInstance;
    public static HumanMineInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public HumanMineInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_HumanMineInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_HumanMineInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 humanGuid = 1;
    public static final int HUMANGUID_FIELD_NUMBER = 1;
    private long humanGuid_;
    public boolean hasHumanGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getHumanGuid() {
      return humanGuid_;
    }
    
    // repeated .com.hifun.soul.proto.common.MineField mineFields = 2;
    public static final int MINEFIELDS_FIELD_NUMBER = 2;
    private java.util.List<com.hifun.soul.proto.common.Mine.MineField> mineFields_;
    public java.util.List<com.hifun.soul.proto.common.Mine.MineField> getMineFieldsList() {
      return mineFields_;
    }
    public java.util.List<? extends com.hifun.soul.proto.common.Mine.MineFieldOrBuilder> 
        getMineFieldsOrBuilderList() {
      return mineFields_;
    }
    public int getMineFieldsCount() {
      return mineFields_.size();
    }
    public com.hifun.soul.proto.common.Mine.MineField getMineFields(int index) {
      return mineFields_.get(index);
    }
    public com.hifun.soul.proto.common.Mine.MineFieldOrBuilder getMineFieldsOrBuilder(
        int index) {
      return mineFields_.get(index);
    }
    
    // optional int32 remainFreeMineNum = 3;
    public static final int REMAINFREEMINENUM_FIELD_NUMBER = 3;
    private int remainFreeMineNum_;
    public boolean hasRemainFreeMineNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRemainFreeMineNum() {
      return remainFreeMineNum_;
    }
    
    // optional int32 buyMineFieldNum = 4;
    public static final int BUYMINEFIELDNUM_FIELD_NUMBER = 4;
    private int buyMineFieldNum_;
    public boolean hasBuyMineFieldNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getBuyMineFieldNum() {
      return buyMineFieldNum_;
    }
    
    // optional int32 resetMineFieldNum = 5;
    public static final int RESETMINEFIELDNUM_FIELD_NUMBER = 5;
    private int resetMineFieldNum_;
    public boolean hasResetMineFieldNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getResetMineFieldNum() {
      return resetMineFieldNum_;
    }
    
    // optional int32 remainBoughtMineNum = 6;
    public static final int REMAINBOUGHTMINENUM_FIELD_NUMBER = 6;
    private int remainBoughtMineNum_;
    public boolean hasRemainBoughtMineNum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getRemainBoughtMineNum() {
      return remainBoughtMineNum_;
    }
    
    private void initFields() {
      humanGuid_ = 0L;
      mineFields_ = java.util.Collections.emptyList();
      remainFreeMineNum_ = 0;
      buyMineFieldNum_ = 0;
      resetMineFieldNum_ = 0;
      remainBoughtMineNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHumanGuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMineFieldsCount(); i++) {
        if (!getMineFields(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, humanGuid_);
      }
      for (int i = 0; i < mineFields_.size(); i++) {
        output.writeMessage(2, mineFields_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, remainFreeMineNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, buyMineFieldNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, resetMineFieldNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, remainBoughtMineNum_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, humanGuid_);
      }
      for (int i = 0; i < mineFields_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, mineFields_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, remainFreeMineNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, buyMineFieldNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, resetMineFieldNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, remainBoughtMineNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.HumanMineInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Mine.HumanMineInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Mine.HumanMineInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_HumanMineInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_HumanMineInfo_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Mine.HumanMineInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMineFieldsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        humanGuid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (mineFieldsBuilder_ == null) {
          mineFields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          mineFieldsBuilder_.clear();
        }
        remainFreeMineNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        buyMineFieldNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        resetMineFieldNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        remainBoughtMineNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Mine.HumanMineInfo.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Mine.HumanMineInfo getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Mine.HumanMineInfo.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Mine.HumanMineInfo build() {
        com.hifun.soul.proto.common.Mine.HumanMineInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Mine.HumanMineInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Mine.HumanMineInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Mine.HumanMineInfo buildPartial() {
        com.hifun.soul.proto.common.Mine.HumanMineInfo result = new com.hifun.soul.proto.common.Mine.HumanMineInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.humanGuid_ = humanGuid_;
        if (mineFieldsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            mineFields_ = java.util.Collections.unmodifiableList(mineFields_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.mineFields_ = mineFields_;
        } else {
          result.mineFields_ = mineFieldsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.remainFreeMineNum_ = remainFreeMineNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buyMineFieldNum_ = buyMineFieldNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.resetMineFieldNum_ = resetMineFieldNum_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.remainBoughtMineNum_ = remainBoughtMineNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Mine.HumanMineInfo) {
          return mergeFrom((com.hifun.soul.proto.common.Mine.HumanMineInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Mine.HumanMineInfo other) {
        if (other == com.hifun.soul.proto.common.Mine.HumanMineInfo.getDefaultInstance()) return this;
        if (other.hasHumanGuid()) {
          setHumanGuid(other.getHumanGuid());
        }
        if (mineFieldsBuilder_ == null) {
          if (!other.mineFields_.isEmpty()) {
            if (mineFields_.isEmpty()) {
              mineFields_ = other.mineFields_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMineFieldsIsMutable();
              mineFields_.addAll(other.mineFields_);
            }
            onChanged();
          }
        } else {
          if (!other.mineFields_.isEmpty()) {
            if (mineFieldsBuilder_.isEmpty()) {
              mineFieldsBuilder_.dispose();
              mineFieldsBuilder_ = null;
              mineFields_ = other.mineFields_;
              bitField0_ = (bitField0_ & ~0x00000002);
              mineFieldsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMineFieldsFieldBuilder() : null;
            } else {
              mineFieldsBuilder_.addAllMessages(other.mineFields_);
            }
          }
        }
        if (other.hasRemainFreeMineNum()) {
          setRemainFreeMineNum(other.getRemainFreeMineNum());
        }
        if (other.hasBuyMineFieldNum()) {
          setBuyMineFieldNum(other.getBuyMineFieldNum());
        }
        if (other.hasResetMineFieldNum()) {
          setResetMineFieldNum(other.getResetMineFieldNum());
        }
        if (other.hasRemainBoughtMineNum()) {
          setRemainBoughtMineNum(other.getRemainBoughtMineNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHumanGuid()) {
          
          return false;
        }
        for (int i = 0; i < getMineFieldsCount(); i++) {
          if (!getMineFields(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              humanGuid_ = input.readInt64();
              break;
            }
            case 18: {
              com.hifun.soul.proto.common.Mine.MineField.Builder subBuilder = com.hifun.soul.proto.common.Mine.MineField.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMineFields(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              remainFreeMineNum_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              buyMineFieldNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              resetMineFieldNum_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              remainBoughtMineNum_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 humanGuid = 1;
      private long humanGuid_ ;
      public boolean hasHumanGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getHumanGuid() {
        return humanGuid_;
      }
      public Builder setHumanGuid(long value) {
        bitField0_ |= 0x00000001;
        humanGuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearHumanGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        humanGuid_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .com.hifun.soul.proto.common.MineField mineFields = 2;
      private java.util.List<com.hifun.soul.proto.common.Mine.MineField> mineFields_ =
        java.util.Collections.emptyList();
      private void ensureMineFieldsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          mineFields_ = new java.util.ArrayList<com.hifun.soul.proto.common.Mine.MineField>(mineFields_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hifun.soul.proto.common.Mine.MineField, com.hifun.soul.proto.common.Mine.MineField.Builder, com.hifun.soul.proto.common.Mine.MineFieldOrBuilder> mineFieldsBuilder_;
      
      public java.util.List<com.hifun.soul.proto.common.Mine.MineField> getMineFieldsList() {
        if (mineFieldsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mineFields_);
        } else {
          return mineFieldsBuilder_.getMessageList();
        }
      }
      public int getMineFieldsCount() {
        if (mineFieldsBuilder_ == null) {
          return mineFields_.size();
        } else {
          return mineFieldsBuilder_.getCount();
        }
      }
      public com.hifun.soul.proto.common.Mine.MineField getMineFields(int index) {
        if (mineFieldsBuilder_ == null) {
          return mineFields_.get(index);
        } else {
          return mineFieldsBuilder_.getMessage(index);
        }
      }
      public Builder setMineFields(
          int index, com.hifun.soul.proto.common.Mine.MineField value) {
        if (mineFieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMineFieldsIsMutable();
          mineFields_.set(index, value);
          onChanged();
        } else {
          mineFieldsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMineFields(
          int index, com.hifun.soul.proto.common.Mine.MineField.Builder builderForValue) {
        if (mineFieldsBuilder_ == null) {
          ensureMineFieldsIsMutable();
          mineFields_.set(index, builderForValue.build());
          onChanged();
        } else {
          mineFieldsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMineFields(com.hifun.soul.proto.common.Mine.MineField value) {
        if (mineFieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMineFieldsIsMutable();
          mineFields_.add(value);
          onChanged();
        } else {
          mineFieldsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMineFields(
          int index, com.hifun.soul.proto.common.Mine.MineField value) {
        if (mineFieldsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMineFieldsIsMutable();
          mineFields_.add(index, value);
          onChanged();
        } else {
          mineFieldsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMineFields(
          com.hifun.soul.proto.common.Mine.MineField.Builder builderForValue) {
        if (mineFieldsBuilder_ == null) {
          ensureMineFieldsIsMutable();
          mineFields_.add(builderForValue.build());
          onChanged();
        } else {
          mineFieldsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMineFields(
          int index, com.hifun.soul.proto.common.Mine.MineField.Builder builderForValue) {
        if (mineFieldsBuilder_ == null) {
          ensureMineFieldsIsMutable();
          mineFields_.add(index, builderForValue.build());
          onChanged();
        } else {
          mineFieldsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMineFields(
          java.lang.Iterable<? extends com.hifun.soul.proto.common.Mine.MineField> values) {
        if (mineFieldsBuilder_ == null) {
          ensureMineFieldsIsMutable();
          super.addAll(values, mineFields_);
          onChanged();
        } else {
          mineFieldsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMineFields() {
        if (mineFieldsBuilder_ == null) {
          mineFields_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          mineFieldsBuilder_.clear();
        }
        return this;
      }
      public Builder removeMineFields(int index) {
        if (mineFieldsBuilder_ == null) {
          ensureMineFieldsIsMutable();
          mineFields_.remove(index);
          onChanged();
        } else {
          mineFieldsBuilder_.remove(index);
        }
        return this;
      }
      public com.hifun.soul.proto.common.Mine.MineField.Builder getMineFieldsBuilder(
          int index) {
        return getMineFieldsFieldBuilder().getBuilder(index);
      }
      public com.hifun.soul.proto.common.Mine.MineFieldOrBuilder getMineFieldsOrBuilder(
          int index) {
        if (mineFieldsBuilder_ == null) {
          return mineFields_.get(index);  } else {
          return mineFieldsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.hifun.soul.proto.common.Mine.MineFieldOrBuilder> 
           getMineFieldsOrBuilderList() {
        if (mineFieldsBuilder_ != null) {
          return mineFieldsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mineFields_);
        }
      }
      public com.hifun.soul.proto.common.Mine.MineField.Builder addMineFieldsBuilder() {
        return getMineFieldsFieldBuilder().addBuilder(
            com.hifun.soul.proto.common.Mine.MineField.getDefaultInstance());
      }
      public com.hifun.soul.proto.common.Mine.MineField.Builder addMineFieldsBuilder(
          int index) {
        return getMineFieldsFieldBuilder().addBuilder(
            index, com.hifun.soul.proto.common.Mine.MineField.getDefaultInstance());
      }
      public java.util.List<com.hifun.soul.proto.common.Mine.MineField.Builder> 
           getMineFieldsBuilderList() {
        return getMineFieldsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hifun.soul.proto.common.Mine.MineField, com.hifun.soul.proto.common.Mine.MineField.Builder, com.hifun.soul.proto.common.Mine.MineFieldOrBuilder> 
          getMineFieldsFieldBuilder() {
        if (mineFieldsBuilder_ == null) {
          mineFieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hifun.soul.proto.common.Mine.MineField, com.hifun.soul.proto.common.Mine.MineField.Builder, com.hifun.soul.proto.common.Mine.MineFieldOrBuilder>(
                  mineFields_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          mineFields_ = null;
        }
        return mineFieldsBuilder_;
      }
      
      // optional int32 remainFreeMineNum = 3;
      private int remainFreeMineNum_ ;
      public boolean hasRemainFreeMineNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRemainFreeMineNum() {
        return remainFreeMineNum_;
      }
      public Builder setRemainFreeMineNum(int value) {
        bitField0_ |= 0x00000004;
        remainFreeMineNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearRemainFreeMineNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        remainFreeMineNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 buyMineFieldNum = 4;
      private int buyMineFieldNum_ ;
      public boolean hasBuyMineFieldNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getBuyMineFieldNum() {
        return buyMineFieldNum_;
      }
      public Builder setBuyMineFieldNum(int value) {
        bitField0_ |= 0x00000008;
        buyMineFieldNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearBuyMineFieldNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        buyMineFieldNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 resetMineFieldNum = 5;
      private int resetMineFieldNum_ ;
      public boolean hasResetMineFieldNum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getResetMineFieldNum() {
        return resetMineFieldNum_;
      }
      public Builder setResetMineFieldNum(int value) {
        bitField0_ |= 0x00000010;
        resetMineFieldNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearResetMineFieldNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        resetMineFieldNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 remainBoughtMineNum = 6;
      private int remainBoughtMineNum_ ;
      public boolean hasRemainBoughtMineNum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getRemainBoughtMineNum() {
        return remainBoughtMineNum_;
      }
      public Builder setRemainBoughtMineNum(int value) {
        bitField0_ |= 0x00000020;
        remainBoughtMineNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearRemainBoughtMineNum() {
        bitField0_ = (bitField0_ & ~0x00000020);
        remainBoughtMineNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.HumanMineInfo)
    }
    
    static {
      defaultInstance = new HumanMineInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.HumanMineInfo)
  }
  
  public interface MineFieldOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 index = 1;
    boolean hasIndex();
    int getIndex();
    
    // required int32 type = 2;
    boolean hasType();
    int getType();
  }
  public static final class MineField extends
      com.google.protobuf.GeneratedMessage
      implements MineFieldOrBuilder {
    // Use MineField.newBuilder() to construct.
    private MineField(Builder builder) {
      super(builder);
    }
    private MineField(boolean noInit) {}
    
    private static final MineField defaultInstance;
    public static MineField getDefaultInstance() {
      return defaultInstance;
    }
    
    public MineField getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_MineField_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_MineField_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 index = 1;
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getIndex() {
      return index_;
    }
    
    // required int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getType() {
      return type_;
    }
    
    private void initFields() {
      index_ = 0;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Mine.MineField parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Mine.MineField prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Mine.MineFieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_MineField_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Mine.internal_static_com_hifun_soul_proto_common_MineField_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Mine.MineField.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Mine.MineField.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Mine.MineField getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Mine.MineField.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Mine.MineField build() {
        com.hifun.soul.proto.common.Mine.MineField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Mine.MineField buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Mine.MineField result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Mine.MineField buildPartial() {
        com.hifun.soul.proto.common.Mine.MineField result = new com.hifun.soul.proto.common.Mine.MineField(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.index_ = index_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Mine.MineField) {
          return mergeFrom((com.hifun.soul.proto.common.Mine.MineField)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Mine.MineField other) {
        if (other == com.hifun.soul.proto.common.Mine.MineField.getDefaultInstance()) return this;
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasIndex()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              index_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 index = 1;
      private int index_ ;
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getIndex() {
        return index_;
      }
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000001;
        index_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 type = 2;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.MineField)
    }
    
    static {
      defaultInstance = new MineField(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.MineField)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_HumanMineInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_HumanMineInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_MineField_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_MineField_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nMine.proto\022\033com.hifun.soul.proto.commo" +
      "n\"\312\001\n\rHumanMineInfo\022\021\n\thumanGuid\030\001 \002(\003\022:" +
      "\n\nmineFields\030\002 \003(\0132&.com.hifun.soul.prot" +
      "o.common.MineField\022\031\n\021remainFreeMineNum\030" +
      "\003 \001(\005\022\027\n\017buyMineFieldNum\030\004 \001(\005\022\031\n\021resetM" +
      "ineFieldNum\030\005 \001(\005\022\033\n\023remainBoughtMineNum" +
      "\030\006 \001(\005\"(\n\tMineField\022\r\n\005index\030\001 \002(\005\022\014\n\004ty" +
      "pe\030\002 \002(\005B#\n\033com.hifun.soul.proto.commonB" +
      "\004Mine"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hifun_soul_proto_common_HumanMineInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hifun_soul_proto_common_HumanMineInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_HumanMineInfo_descriptor,
              new java.lang.String[] { "HumanGuid", "MineFields", "RemainFreeMineNum", "BuyMineFieldNum", "ResetMineFieldNum", "RemainBoughtMineNum", },
              com.hifun.soul.proto.common.Mine.HumanMineInfo.class,
              com.hifun.soul.proto.common.Mine.HumanMineInfo.Builder.class);
          internal_static_com_hifun_soul_proto_common_MineField_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_hifun_soul_proto_common_MineField_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_MineField_descriptor,
              new java.lang.String[] { "Index", "Type", },
              com.hifun.soul.proto.common.Mine.MineField.class,
              com.hifun.soul.proto.common.Mine.MineField.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
