// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quest.proto

package com.hifun.soul.proto.common;

public final class Quests {
  private Quests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QuestFinishDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 questId = 1;
    boolean hasQuestId();
    int getQuestId();
  }
  public static final class QuestFinishData extends
      com.google.protobuf.GeneratedMessage
      implements QuestFinishDataOrBuilder {
    // Use QuestFinishData.newBuilder() to construct.
    private QuestFinishData(Builder builder) {
      super(builder);
    }
    private QuestFinishData(boolean noInit) {}
    
    private static final QuestFinishData defaultInstance;
    public static QuestFinishData getDefaultInstance() {
      return defaultInstance;
    }
    
    public QuestFinishData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestFinishData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestFinishData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 questId = 1;
    public static final int QUESTID_FIELD_NUMBER = 1;
    private int questId_;
    public boolean hasQuestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getQuestId() {
      return questId_;
    }
    
    private void initFields() {
      questId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasQuestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, questId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, questId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestFinishData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Quests.QuestFinishData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Quests.QuestFinishDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestFinishData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestFinishData_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Quests.QuestFinishData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        questId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Quests.QuestFinishData.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Quests.QuestFinishData getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Quests.QuestFinishData.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Quests.QuestFinishData build() {
        com.hifun.soul.proto.common.Quests.QuestFinishData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Quests.QuestFinishData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Quests.QuestFinishData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Quests.QuestFinishData buildPartial() {
        com.hifun.soul.proto.common.Quests.QuestFinishData result = new com.hifun.soul.proto.common.Quests.QuestFinishData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.questId_ = questId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Quests.QuestFinishData) {
          return mergeFrom((com.hifun.soul.proto.common.Quests.QuestFinishData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Quests.QuestFinishData other) {
        if (other == com.hifun.soul.proto.common.Quests.QuestFinishData.getDefaultInstance()) return this;
        if (other.hasQuestId()) {
          setQuestId(other.getQuestId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasQuestId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              questId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 questId = 1;
      private int questId_ ;
      public boolean hasQuestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getQuestId() {
        return questId_;
      }
      public Builder setQuestId(int value) {
        bitField0_ |= 0x00000001;
        questId_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        questId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.QuestFinishData)
    }
    
    static {
      defaultInstance = new QuestFinishData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.QuestFinishData)
  }
  
  public interface QuestStateDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 questId = 1;
    boolean hasQuestId();
    int getQuestId();
    
    // repeated .com.hifun.soul.proto.common.QuestAimCounterData aimCounter = 2;
    java.util.List<com.hifun.soul.proto.common.Quests.QuestAimCounterData> 
        getAimCounterList();
    com.hifun.soul.proto.common.Quests.QuestAimCounterData getAimCounter(int index);
    int getAimCounterCount();
    java.util.List<? extends com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder> 
        getAimCounterOrBuilderList();
    com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder getAimCounterOrBuilder(
        int index);
    
    // optional int32 state = 3;
    boolean hasState();
    int getState();
    
    // optional int64 endTime = 4;
    boolean hasEndTime();
    long getEndTime();
  }
  public static final class QuestStateData extends
      com.google.protobuf.GeneratedMessage
      implements QuestStateDataOrBuilder {
    // Use QuestStateData.newBuilder() to construct.
    private QuestStateData(Builder builder) {
      super(builder);
    }
    private QuestStateData(boolean noInit) {}
    
    private static final QuestStateData defaultInstance;
    public static QuestStateData getDefaultInstance() {
      return defaultInstance;
    }
    
    public QuestStateData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestStateData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestStateData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 questId = 1;
    public static final int QUESTID_FIELD_NUMBER = 1;
    private int questId_;
    public boolean hasQuestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getQuestId() {
      return questId_;
    }
    
    // repeated .com.hifun.soul.proto.common.QuestAimCounterData aimCounter = 2;
    public static final int AIMCOUNTER_FIELD_NUMBER = 2;
    private java.util.List<com.hifun.soul.proto.common.Quests.QuestAimCounterData> aimCounter_;
    public java.util.List<com.hifun.soul.proto.common.Quests.QuestAimCounterData> getAimCounterList() {
      return aimCounter_;
    }
    public java.util.List<? extends com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder> 
        getAimCounterOrBuilderList() {
      return aimCounter_;
    }
    public int getAimCounterCount() {
      return aimCounter_.size();
    }
    public com.hifun.soul.proto.common.Quests.QuestAimCounterData getAimCounter(int index) {
      return aimCounter_.get(index);
    }
    public com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder getAimCounterOrBuilder(
        int index) {
      return aimCounter_.get(index);
    }
    
    // optional int32 state = 3;
    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getState() {
      return state_;
    }
    
    // optional int64 endTime = 4;
    public static final int ENDTIME_FIELD_NUMBER = 4;
    private long endTime_;
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getEndTime() {
      return endTime_;
    }
    
    private void initFields() {
      questId_ = 0;
      aimCounter_ = java.util.Collections.emptyList();
      state_ = 0;
      endTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasQuestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAimCounterCount(); i++) {
        if (!getAimCounter(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, questId_);
      }
      for (int i = 0; i < aimCounter_.size(); i++) {
        output.writeMessage(2, aimCounter_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, endTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, questId_);
      }
      for (int i = 0; i < aimCounter_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, aimCounter_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, endTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestStateData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Quests.QuestStateData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Quests.QuestStateDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestStateData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestStateData_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Quests.QuestStateData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAimCounterFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        questId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (aimCounterBuilder_ == null) {
          aimCounter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          aimCounterBuilder_.clear();
        }
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Quests.QuestStateData.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Quests.QuestStateData getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Quests.QuestStateData.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Quests.QuestStateData build() {
        com.hifun.soul.proto.common.Quests.QuestStateData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Quests.QuestStateData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Quests.QuestStateData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Quests.QuestStateData buildPartial() {
        com.hifun.soul.proto.common.Quests.QuestStateData result = new com.hifun.soul.proto.common.Quests.QuestStateData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.questId_ = questId_;
        if (aimCounterBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            aimCounter_ = java.util.Collections.unmodifiableList(aimCounter_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.aimCounter_ = aimCounter_;
        } else {
          result.aimCounter_ = aimCounterBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endTime_ = endTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Quests.QuestStateData) {
          return mergeFrom((com.hifun.soul.proto.common.Quests.QuestStateData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Quests.QuestStateData other) {
        if (other == com.hifun.soul.proto.common.Quests.QuestStateData.getDefaultInstance()) return this;
        if (other.hasQuestId()) {
          setQuestId(other.getQuestId());
        }
        if (aimCounterBuilder_ == null) {
          if (!other.aimCounter_.isEmpty()) {
            if (aimCounter_.isEmpty()) {
              aimCounter_ = other.aimCounter_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAimCounterIsMutable();
              aimCounter_.addAll(other.aimCounter_);
            }
            onChanged();
          }
        } else {
          if (!other.aimCounter_.isEmpty()) {
            if (aimCounterBuilder_.isEmpty()) {
              aimCounterBuilder_.dispose();
              aimCounterBuilder_ = null;
              aimCounter_ = other.aimCounter_;
              bitField0_ = (bitField0_ & ~0x00000002);
              aimCounterBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAimCounterFieldBuilder() : null;
            } else {
              aimCounterBuilder_.addAllMessages(other.aimCounter_);
            }
          }
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasQuestId()) {
          
          return false;
        }
        for (int i = 0; i < getAimCounterCount(); i++) {
          if (!getAimCounter(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              questId_ = input.readInt32();
              break;
            }
            case 18: {
              com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder subBuilder = com.hifun.soul.proto.common.Quests.QuestAimCounterData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAimCounter(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              state_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              endTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 questId = 1;
      private int questId_ ;
      public boolean hasQuestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getQuestId() {
        return questId_;
      }
      public Builder setQuestId(int value) {
        bitField0_ |= 0x00000001;
        questId_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        questId_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.hifun.soul.proto.common.QuestAimCounterData aimCounter = 2;
      private java.util.List<com.hifun.soul.proto.common.Quests.QuestAimCounterData> aimCounter_ =
        java.util.Collections.emptyList();
      private void ensureAimCounterIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          aimCounter_ = new java.util.ArrayList<com.hifun.soul.proto.common.Quests.QuestAimCounterData>(aimCounter_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hifun.soul.proto.common.Quests.QuestAimCounterData, com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder, com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder> aimCounterBuilder_;
      
      public java.util.List<com.hifun.soul.proto.common.Quests.QuestAimCounterData> getAimCounterList() {
        if (aimCounterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(aimCounter_);
        } else {
          return aimCounterBuilder_.getMessageList();
        }
      }
      public int getAimCounterCount() {
        if (aimCounterBuilder_ == null) {
          return aimCounter_.size();
        } else {
          return aimCounterBuilder_.getCount();
        }
      }
      public com.hifun.soul.proto.common.Quests.QuestAimCounterData getAimCounter(int index) {
        if (aimCounterBuilder_ == null) {
          return aimCounter_.get(index);
        } else {
          return aimCounterBuilder_.getMessage(index);
        }
      }
      public Builder setAimCounter(
          int index, com.hifun.soul.proto.common.Quests.QuestAimCounterData value) {
        if (aimCounterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAimCounterIsMutable();
          aimCounter_.set(index, value);
          onChanged();
        } else {
          aimCounterBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAimCounter(
          int index, com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder builderForValue) {
        if (aimCounterBuilder_ == null) {
          ensureAimCounterIsMutable();
          aimCounter_.set(index, builderForValue.build());
          onChanged();
        } else {
          aimCounterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAimCounter(com.hifun.soul.proto.common.Quests.QuestAimCounterData value) {
        if (aimCounterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAimCounterIsMutable();
          aimCounter_.add(value);
          onChanged();
        } else {
          aimCounterBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAimCounter(
          int index, com.hifun.soul.proto.common.Quests.QuestAimCounterData value) {
        if (aimCounterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAimCounterIsMutable();
          aimCounter_.add(index, value);
          onChanged();
        } else {
          aimCounterBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAimCounter(
          com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder builderForValue) {
        if (aimCounterBuilder_ == null) {
          ensureAimCounterIsMutable();
          aimCounter_.add(builderForValue.build());
          onChanged();
        } else {
          aimCounterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAimCounter(
          int index, com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder builderForValue) {
        if (aimCounterBuilder_ == null) {
          ensureAimCounterIsMutable();
          aimCounter_.add(index, builderForValue.build());
          onChanged();
        } else {
          aimCounterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAimCounter(
          java.lang.Iterable<? extends com.hifun.soul.proto.common.Quests.QuestAimCounterData> values) {
        if (aimCounterBuilder_ == null) {
          ensureAimCounterIsMutable();
          super.addAll(values, aimCounter_);
          onChanged();
        } else {
          aimCounterBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAimCounter() {
        if (aimCounterBuilder_ == null) {
          aimCounter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          aimCounterBuilder_.clear();
        }
        return this;
      }
      public Builder removeAimCounter(int index) {
        if (aimCounterBuilder_ == null) {
          ensureAimCounterIsMutable();
          aimCounter_.remove(index);
          onChanged();
        } else {
          aimCounterBuilder_.remove(index);
        }
        return this;
      }
      public com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder getAimCounterBuilder(
          int index) {
        return getAimCounterFieldBuilder().getBuilder(index);
      }
      public com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder getAimCounterOrBuilder(
          int index) {
        if (aimCounterBuilder_ == null) {
          return aimCounter_.get(index);  } else {
          return aimCounterBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder> 
           getAimCounterOrBuilderList() {
        if (aimCounterBuilder_ != null) {
          return aimCounterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(aimCounter_);
        }
      }
      public com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder addAimCounterBuilder() {
        return getAimCounterFieldBuilder().addBuilder(
            com.hifun.soul.proto.common.Quests.QuestAimCounterData.getDefaultInstance());
      }
      public com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder addAimCounterBuilder(
          int index) {
        return getAimCounterFieldBuilder().addBuilder(
            index, com.hifun.soul.proto.common.Quests.QuestAimCounterData.getDefaultInstance());
      }
      public java.util.List<com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder> 
           getAimCounterBuilderList() {
        return getAimCounterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.hifun.soul.proto.common.Quests.QuestAimCounterData, com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder, com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder> 
          getAimCounterFieldBuilder() {
        if (aimCounterBuilder_ == null) {
          aimCounterBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.hifun.soul.proto.common.Quests.QuestAimCounterData, com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder, com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder>(
                  aimCounter_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          aimCounter_ = null;
        }
        return aimCounterBuilder_;
      }
      
      // optional int32 state = 3;
      private int state_ ;
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getState() {
        return state_;
      }
      public Builder setState(int value) {
        bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 endTime = 4;
      private long endTime_ ;
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getEndTime() {
        return endTime_;
      }
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000008;
        endTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        endTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.QuestStateData)
    }
    
    static {
      defaultInstance = new QuestStateData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.QuestStateData)
  }
  
  public interface QuestAimCounterDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 aimIndex = 1;
    boolean hasAimIndex();
    int getAimIndex();
    
    // required int32 value = 2;
    boolean hasValue();
    int getValue();
    
    // optional int32 aimType = 3;
    boolean hasAimType();
    int getAimType();
  }
  public static final class QuestAimCounterData extends
      com.google.protobuf.GeneratedMessage
      implements QuestAimCounterDataOrBuilder {
    // Use QuestAimCounterData.newBuilder() to construct.
    private QuestAimCounterData(Builder builder) {
      super(builder);
    }
    private QuestAimCounterData(boolean noInit) {}
    
    private static final QuestAimCounterData defaultInstance;
    public static QuestAimCounterData getDefaultInstance() {
      return defaultInstance;
    }
    
    public QuestAimCounterData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestAimCounterData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestAimCounterData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 aimIndex = 1;
    public static final int AIMINDEX_FIELD_NUMBER = 1;
    private int aimIndex_;
    public boolean hasAimIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAimIndex() {
      return aimIndex_;
    }
    
    // required int32 value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getValue() {
      return value_;
    }
    
    // optional int32 aimType = 3;
    public static final int AIMTYPE_FIELD_NUMBER = 3;
    private int aimType_;
    public boolean hasAimType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getAimType() {
      return aimType_;
    }
    
    private void initFields() {
      aimIndex_ = 0;
      value_ = 0;
      aimType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAimIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, aimIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, aimType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, aimIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, aimType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.QuestAimCounterData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Quests.QuestAimCounterData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Quests.QuestAimCounterDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestAimCounterData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_QuestAimCounterData_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Quests.QuestAimCounterData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        aimIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        aimType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Quests.QuestAimCounterData.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Quests.QuestAimCounterData getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Quests.QuestAimCounterData.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Quests.QuestAimCounterData build() {
        com.hifun.soul.proto.common.Quests.QuestAimCounterData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Quests.QuestAimCounterData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Quests.QuestAimCounterData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Quests.QuestAimCounterData buildPartial() {
        com.hifun.soul.proto.common.Quests.QuestAimCounterData result = new com.hifun.soul.proto.common.Quests.QuestAimCounterData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.aimIndex_ = aimIndex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.aimType_ = aimType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Quests.QuestAimCounterData) {
          return mergeFrom((com.hifun.soul.proto.common.Quests.QuestAimCounterData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Quests.QuestAimCounterData other) {
        if (other == com.hifun.soul.proto.common.Quests.QuestAimCounterData.getDefaultInstance()) return this;
        if (other.hasAimIndex()) {
          setAimIndex(other.getAimIndex());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasAimType()) {
          setAimType(other.getAimType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAimIndex()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              aimIndex_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              aimType_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 aimIndex = 1;
      private int aimIndex_ ;
      public boolean hasAimIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAimIndex() {
        return aimIndex_;
      }
      public Builder setAimIndex(int value) {
        bitField0_ |= 0x00000001;
        aimIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearAimIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aimIndex_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 value = 2;
      private int value_ ;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getValue() {
        return value_;
      }
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 aimType = 3;
      private int aimType_ ;
      public boolean hasAimType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAimType() {
        return aimType_;
      }
      public Builder setAimType(int value) {
        bitField0_ |= 0x00000004;
        aimType_ = value;
        onChanged();
        return this;
      }
      public Builder clearAimType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        aimType_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.QuestAimCounterData)
    }
    
    static {
      defaultInstance = new QuestAimCounterData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.QuestAimCounterData)
  }
  
  public interface DailyQuestRewardBoxOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 boxId = 1;
    boolean hasBoxId();
    int getBoxId();
    
    // required int32 state = 2;
    boolean hasState();
    int getState();
  }
  public static final class DailyQuestRewardBox extends
      com.google.protobuf.GeneratedMessage
      implements DailyQuestRewardBoxOrBuilder {
    // Use DailyQuestRewardBox.newBuilder() to construct.
    private DailyQuestRewardBox(Builder builder) {
      super(builder);
    }
    private DailyQuestRewardBox(boolean noInit) {}
    
    private static final DailyQuestRewardBox defaultInstance;
    public static DailyQuestRewardBox getDefaultInstance() {
      return defaultInstance;
    }
    
    public DailyQuestRewardBox getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 boxId = 1;
    public static final int BOXID_FIELD_NUMBER = 1;
    private int boxId_;
    public boolean hasBoxId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getBoxId() {
      return boxId_;
    }
    
    // required int32 state = 2;
    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getState() {
      return state_;
    }
    
    private void initFields() {
      boxId_ = 0;
      state_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBoxId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, boxId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, state_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, boxId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Quests.DailyQuestRewardBox parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Quests.DailyQuestRewardBox prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Quests.DailyQuestRewardBoxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Quests.internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Quests.DailyQuestRewardBox.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        boxId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Quests.DailyQuestRewardBox.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Quests.DailyQuestRewardBox getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Quests.DailyQuestRewardBox.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Quests.DailyQuestRewardBox build() {
        com.hifun.soul.proto.common.Quests.DailyQuestRewardBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Quests.DailyQuestRewardBox buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Quests.DailyQuestRewardBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Quests.DailyQuestRewardBox buildPartial() {
        com.hifun.soul.proto.common.Quests.DailyQuestRewardBox result = new com.hifun.soul.proto.common.Quests.DailyQuestRewardBox(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.boxId_ = boxId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Quests.DailyQuestRewardBox) {
          return mergeFrom((com.hifun.soul.proto.common.Quests.DailyQuestRewardBox)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Quests.DailyQuestRewardBox other) {
        if (other == com.hifun.soul.proto.common.Quests.DailyQuestRewardBox.getDefaultInstance()) return this;
        if (other.hasBoxId()) {
          setBoxId(other.getBoxId());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBoxId()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              boxId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              state_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 boxId = 1;
      private int boxId_ ;
      public boolean hasBoxId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getBoxId() {
        return boxId_;
      }
      public Builder setBoxId(int value) {
        bitField0_ |= 0x00000001;
        boxId_ = value;
        onChanged();
        return this;
      }
      public Builder clearBoxId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        boxId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 state = 2;
      private int state_ ;
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getState() {
        return state_;
      }
      public Builder setState(int value) {
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.DailyQuestRewardBox)
    }
    
    static {
      defaultInstance = new DailyQuestRewardBox(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.DailyQuestRewardBox)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_QuestFinishData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_QuestFinishData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_QuestStateData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_QuestStateData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_QuestAimCounterData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_QuestAimCounterData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Quest.proto\022\033com.hifun.soul.proto.comm" +
      "on\"\"\n\017QuestFinishData\022\017\n\007questId\030\001 \002(\005\"\207" +
      "\001\n\016QuestStateData\022\017\n\007questId\030\001 \002(\005\022D\n\nai" +
      "mCounter\030\002 \003(\01320.com.hifun.soul.proto.co" +
      "mmon.QuestAimCounterData\022\r\n\005state\030\003 \001(\005\022" +
      "\017\n\007endTime\030\004 \001(\003\"G\n\023QuestAimCounterData\022" +
      "\020\n\010aimIndex\030\001 \002(\005\022\r\n\005value\030\002 \002(\005\022\017\n\007aimT" +
      "ype\030\003 \001(\005\"3\n\023DailyQuestRewardBox\022\r\n\005boxI" +
      "d\030\001 \002(\005\022\r\n\005state\030\002 \002(\005B%\n\033com.hifun.soul" +
      ".proto.commonB\006Quests"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hifun_soul_proto_common_QuestFinishData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hifun_soul_proto_common_QuestFinishData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_QuestFinishData_descriptor,
              new java.lang.String[] { "QuestId", },
              com.hifun.soul.proto.common.Quests.QuestFinishData.class,
              com.hifun.soul.proto.common.Quests.QuestFinishData.Builder.class);
          internal_static_com_hifun_soul_proto_common_QuestStateData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_hifun_soul_proto_common_QuestStateData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_QuestStateData_descriptor,
              new java.lang.String[] { "QuestId", "AimCounter", "State", "EndTime", },
              com.hifun.soul.proto.common.Quests.QuestStateData.class,
              com.hifun.soul.proto.common.Quests.QuestStateData.Builder.class);
          internal_static_com_hifun_soul_proto_common_QuestAimCounterData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_hifun_soul_proto_common_QuestAimCounterData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_QuestAimCounterData_descriptor,
              new java.lang.String[] { "AimIndex", "Value", "AimType", },
              com.hifun.soul.proto.common.Quests.QuestAimCounterData.class,
              com.hifun.soul.proto.common.Quests.QuestAimCounterData.Builder.class);
          internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_DailyQuestRewardBox_descriptor,
              new java.lang.String[] { "BoxId", "State", },
              com.hifun.soul.proto.common.Quests.DailyQuestRewardBox.class,
              com.hifun.soul.proto.common.Quests.DailyQuestRewardBox.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
