// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stargazer.proto

package com.hifun.soul.proto.common;

public final class Stargazers {
  private Stargazers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StargazerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 stargazerId = 1;
    boolean hasStargazerId();
    int getStargazerId();
    
    // required bool open = 2;
    boolean hasOpen();
    boolean getOpen();
  }
  public static final class Stargazer extends
      com.google.protobuf.GeneratedMessage
      implements StargazerOrBuilder {
    // Use Stargazer.newBuilder() to construct.
    private Stargazer(Builder builder) {
      super(builder);
    }
    private Stargazer(boolean noInit) {}
    
    private static final Stargazer defaultInstance;
    public static Stargazer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Stargazer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Stargazers.internal_static_com_hifun_soul_proto_common_Stargazer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Stargazers.internal_static_com_hifun_soul_proto_common_Stargazer_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 stargazerId = 1;
    public static final int STARGAZERID_FIELD_NUMBER = 1;
    private int stargazerId_;
    public boolean hasStargazerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getStargazerId() {
      return stargazerId_;
    }
    
    // required bool open = 2;
    public static final int OPEN_FIELD_NUMBER = 2;
    private boolean open_;
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getOpen() {
      return open_;
    }
    
    private void initFields() {
      stargazerId_ = 0;
      open_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStargazerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stargazerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, open_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stargazerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, open_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Stargazers.Stargazer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Stargazers.Stargazer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Stargazers.StargazerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Stargazers.internal_static_com_hifun_soul_proto_common_Stargazer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Stargazers.internal_static_com_hifun_soul_proto_common_Stargazer_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Stargazers.Stargazer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        stargazerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        open_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Stargazers.Stargazer.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Stargazers.Stargazer getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Stargazers.Stargazer.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Stargazers.Stargazer build() {
        com.hifun.soul.proto.common.Stargazers.Stargazer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Stargazers.Stargazer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Stargazers.Stargazer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Stargazers.Stargazer buildPartial() {
        com.hifun.soul.proto.common.Stargazers.Stargazer result = new com.hifun.soul.proto.common.Stargazers.Stargazer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stargazerId_ = stargazerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.open_ = open_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Stargazers.Stargazer) {
          return mergeFrom((com.hifun.soul.proto.common.Stargazers.Stargazer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Stargazers.Stargazer other) {
        if (other == com.hifun.soul.proto.common.Stargazers.Stargazer.getDefaultInstance()) return this;
        if (other.hasStargazerId()) {
          setStargazerId(other.getStargazerId());
        }
        if (other.hasOpen()) {
          setOpen(other.getOpen());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStargazerId()) {
          
          return false;
        }
        if (!hasOpen()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stargazerId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              open_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 stargazerId = 1;
      private int stargazerId_ ;
      public boolean hasStargazerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getStargazerId() {
        return stargazerId_;
      }
      public Builder setStargazerId(int value) {
        bitField0_ |= 0x00000001;
        stargazerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearStargazerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stargazerId_ = 0;
        onChanged();
        return this;
      }
      
      // required bool open = 2;
      private boolean open_ ;
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getOpen() {
        return open_;
      }
      public Builder setOpen(boolean value) {
        bitField0_ |= 0x00000002;
        open_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000002);
        open_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.Stargazer)
    }
    
    static {
      defaultInstance = new Stargazer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.Stargazer)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_Stargazer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_Stargazer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Stargazer.proto\022\033com.hifun.soul.proto." +
      "common\".\n\tStargazer\022\023\n\013stargazerId\030\001 \002(\005" +
      "\022\014\n\004open\030\002 \002(\010B)\n\033com.hifun.soul.proto.c" +
      "ommonB\nStargazers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hifun_soul_proto_common_Stargazer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hifun_soul_proto_common_Stargazer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_Stargazer_descriptor,
              new java.lang.String[] { "StargazerId", "Open", },
              com.hifun.soul.proto.common.Stargazers.Stargazer.class,
              com.hifun.soul.proto.common.Stargazers.Stargazer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
