// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Warrior.proto

package com.hifun.soul.proto.common;

public final class Warrior {
  private Warrior() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HumanWarriorInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 humanGuid = 1;
    boolean hasHumanGuid();
    long getHumanGuid();
    
    // optional int32 currentQuestIndex = 2;
    boolean hasCurrentQuestIndex();
    int getCurrentQuestIndex();
    
    // optional int32 currentQuestState = 3;
    boolean hasCurrentQuestState();
    int getCurrentQuestState();
    
    // optional int32 questRewardState = 4;
    boolean hasQuestRewardState();
    int getQuestRewardState();
    
    // optional int32 currentQuestCompleteNum = 5;
    boolean hasCurrentQuestCompleteNum();
    int getCurrentQuestCompleteNum();
  }
  public static final class HumanWarriorInfo extends
      com.google.protobuf.GeneratedMessage
      implements HumanWarriorInfoOrBuilder {
    // Use HumanWarriorInfo.newBuilder() to construct.
    private HumanWarriorInfo(Builder builder) {
      super(builder);
    }
    private HumanWarriorInfo(boolean noInit) {}
    
    private static final HumanWarriorInfo defaultInstance;
    public static HumanWarriorInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public HumanWarriorInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hifun.soul.proto.common.Warrior.internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hifun.soul.proto.common.Warrior.internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 humanGuid = 1;
    public static final int HUMANGUID_FIELD_NUMBER = 1;
    private long humanGuid_;
    public boolean hasHumanGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getHumanGuid() {
      return humanGuid_;
    }
    
    // optional int32 currentQuestIndex = 2;
    public static final int CURRENTQUESTINDEX_FIELD_NUMBER = 2;
    private int currentQuestIndex_;
    public boolean hasCurrentQuestIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCurrentQuestIndex() {
      return currentQuestIndex_;
    }
    
    // optional int32 currentQuestState = 3;
    public static final int CURRENTQUESTSTATE_FIELD_NUMBER = 3;
    private int currentQuestState_;
    public boolean hasCurrentQuestState() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getCurrentQuestState() {
      return currentQuestState_;
    }
    
    // optional int32 questRewardState = 4;
    public static final int QUESTREWARDSTATE_FIELD_NUMBER = 4;
    private int questRewardState_;
    public boolean hasQuestRewardState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getQuestRewardState() {
      return questRewardState_;
    }
    
    // optional int32 currentQuestCompleteNum = 5;
    public static final int CURRENTQUESTCOMPLETENUM_FIELD_NUMBER = 5;
    private int currentQuestCompleteNum_;
    public boolean hasCurrentQuestCompleteNum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getCurrentQuestCompleteNum() {
      return currentQuestCompleteNum_;
    }
    
    private void initFields() {
      humanGuid_ = 0L;
      currentQuestIndex_ = 0;
      currentQuestState_ = 0;
      questRewardState_ = 0;
      currentQuestCompleteNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHumanGuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, humanGuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currentQuestIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, currentQuestState_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, questRewardState_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, currentQuestCompleteNum_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, humanGuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentQuestIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, currentQuestState_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, questRewardState_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, currentQuestCompleteNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.hifun.soul.proto.common.Warrior.HumanWarriorInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hifun.soul.proto.common.Warrior.HumanWarriorInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hifun.soul.proto.common.Warrior.HumanWarriorInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hifun.soul.proto.common.Warrior.internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hifun.soul.proto.common.Warrior.internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_fieldAccessorTable;
      }
      
      // Construct using com.hifun.soul.proto.common.Warrior.HumanWarriorInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        humanGuid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        currentQuestIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        currentQuestState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        questRewardState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        currentQuestCompleteNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hifun.soul.proto.common.Warrior.HumanWarriorInfo.getDescriptor();
      }
      
      public com.hifun.soul.proto.common.Warrior.HumanWarriorInfo getDefaultInstanceForType() {
        return com.hifun.soul.proto.common.Warrior.HumanWarriorInfo.getDefaultInstance();
      }
      
      public com.hifun.soul.proto.common.Warrior.HumanWarriorInfo build() {
        com.hifun.soul.proto.common.Warrior.HumanWarriorInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.hifun.soul.proto.common.Warrior.HumanWarriorInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.hifun.soul.proto.common.Warrior.HumanWarriorInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.hifun.soul.proto.common.Warrior.HumanWarriorInfo buildPartial() {
        com.hifun.soul.proto.common.Warrior.HumanWarriorInfo result = new com.hifun.soul.proto.common.Warrior.HumanWarriorInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.humanGuid_ = humanGuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currentQuestIndex_ = currentQuestIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.currentQuestState_ = currentQuestState_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.questRewardState_ = questRewardState_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.currentQuestCompleteNum_ = currentQuestCompleteNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hifun.soul.proto.common.Warrior.HumanWarriorInfo) {
          return mergeFrom((com.hifun.soul.proto.common.Warrior.HumanWarriorInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.hifun.soul.proto.common.Warrior.HumanWarriorInfo other) {
        if (other == com.hifun.soul.proto.common.Warrior.HumanWarriorInfo.getDefaultInstance()) return this;
        if (other.hasHumanGuid()) {
          setHumanGuid(other.getHumanGuid());
        }
        if (other.hasCurrentQuestIndex()) {
          setCurrentQuestIndex(other.getCurrentQuestIndex());
        }
        if (other.hasCurrentQuestState()) {
          setCurrentQuestState(other.getCurrentQuestState());
        }
        if (other.hasQuestRewardState()) {
          setQuestRewardState(other.getQuestRewardState());
        }
        if (other.hasCurrentQuestCompleteNum()) {
          setCurrentQuestCompleteNum(other.getCurrentQuestCompleteNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHumanGuid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              humanGuid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currentQuestIndex_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              currentQuestState_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              questRewardState_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              currentQuestCompleteNum_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 humanGuid = 1;
      private long humanGuid_ ;
      public boolean hasHumanGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getHumanGuid() {
        return humanGuid_;
      }
      public Builder setHumanGuid(long value) {
        bitField0_ |= 0x00000001;
        humanGuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearHumanGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        humanGuid_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 currentQuestIndex = 2;
      private int currentQuestIndex_ ;
      public boolean hasCurrentQuestIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCurrentQuestIndex() {
        return currentQuestIndex_;
      }
      public Builder setCurrentQuestIndex(int value) {
        bitField0_ |= 0x00000002;
        currentQuestIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentQuestIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentQuestIndex_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 currentQuestState = 3;
      private int currentQuestState_ ;
      public boolean hasCurrentQuestState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCurrentQuestState() {
        return currentQuestState_;
      }
      public Builder setCurrentQuestState(int value) {
        bitField0_ |= 0x00000004;
        currentQuestState_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentQuestState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentQuestState_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 questRewardState = 4;
      private int questRewardState_ ;
      public boolean hasQuestRewardState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getQuestRewardState() {
        return questRewardState_;
      }
      public Builder setQuestRewardState(int value) {
        bitField0_ |= 0x00000008;
        questRewardState_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuestRewardState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        questRewardState_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 currentQuestCompleteNum = 5;
      private int currentQuestCompleteNum_ ;
      public boolean hasCurrentQuestCompleteNum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getCurrentQuestCompleteNum() {
        return currentQuestCompleteNum_;
      }
      public Builder setCurrentQuestCompleteNum(int value) {
        bitField0_ |= 0x00000010;
        currentQuestCompleteNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentQuestCompleteNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        currentQuestCompleteNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.hifun.soul.proto.common.HumanWarriorInfo)
    }
    
    static {
      defaultInstance = new HumanWarriorInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.hifun.soul.proto.common.HumanWarriorInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rWarrior.proto\022\033com.hifun.soul.proto.co" +
      "mmon\"\226\001\n\020HumanWarriorInfo\022\021\n\thumanGuid\030\001" +
      " \002(\003\022\031\n\021currentQuestIndex\030\002 \001(\005\022\031\n\021curre" +
      "ntQuestState\030\003 \001(\005\022\030\n\020questRewardState\030\004" +
      " \001(\005\022\037\n\027currentQuestCompleteNum\030\005 \001(\005B&\n" +
      "\033com.hifun.soul.proto.commonB\007Warrior"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hifun_soul_proto_common_HumanWarriorInfo_descriptor,
              new java.lang.String[] { "HumanGuid", "CurrentQuestIndex", "CurrentQuestState", "QuestRewardState", "CurrentQuestCompleteNum", },
              com.hifun.soul.proto.common.Warrior.HumanWarriorInfo.class,
              com.hifun.soul.proto.common.Warrior.HumanWarriorInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
